/**
 * Pure helpers for Parts network inquiries (RFQ step 4 of the Parts × Shop
 * Manager contract in docs/365_PARTS_PARTNER_NETWORK_PLAN.md).
 *
 * The database only accepts inquiries whose lifecycle fields start empty and
 * whose requester is either nobody (guest) or the signed-in caller. Building
 * the insert row here keeps the server function aligned with those RLS rules.
 */

export type NetworkInquiryInput = {
  business_id: string;
  item_id?: string | null;
  sku?: string | null;
  part_name: string;
  quantity?: number;
  contact_name: string;
  contact_email: string;
  contact_phone?: string | null;
  message?: string | null;
};

/** Columns a buyer may set. Everything else belongs to the partner's response. */
export const NETWORK_INQUIRY_BUYER_COLUMNS = [
  "id",
  "business_id",
  "item_id",
  "sku",
  "part_name",
  "quantity",
  "contact_name",
  "contact_email",
  "contact_phone",
  "message",
  "requester_user_id",
] as const;

export type NetworkInquiryBuyerColumn = (typeof NETWORK_INQUIRY_BUYER_COLUMNS)[number];

export type NetworkInquiryInsertRow = {
  id: string;
  business_id: string;
  item_id: string | null;
  sku: string | null;
  part_name: string;
  quantity: number;
  contact_name: string;
  contact_email: string;
  contact_phone: string | null;
  message: string | null;
  requester_user_id: string | null;
};

/** Partner-owned lifecycle columns that a buyer must never pre-set. */
export const NETWORK_INQUIRY_PARTNER_COLUMNS = [
  "status",
  "response_note",
  "responded_at",
  "responded_by",
  "fulfilled_price",
  "fulfilled_quantity",
  "fulfilled_eta",
  "fulfilled_message",
  "reserved_quantity",
  "reserved_until",
  "reserved_item_id",
] as const;

/**
 * Build the row for `network_part_inquiries`.
 *
 * `id` is generated by the caller so a guest insert can use
 * `return=minimal`: guests have no SELECT policy on inquiries, so asking
 * PostgREST to return the inserted row would be rejected by RLS.
 */
export function buildNetworkInquiryRow(
  input: NetworkInquiryInput,
  opts: { id: string; requesterUserId: string | null },
): NetworkInquiryInsertRow {
  return {
    id: opts.id,
    business_id: input.business_id,
    item_id: input.item_id ?? null,
    sku: input.sku ?? null,
    part_name: input.part_name,
    quantity: input.quantity ?? 1,
    contact_name: input.contact_name,
    contact_email: input.contact_email,
    contact_phone: input.contact_phone ?? null,
    message: input.message ?? null,
    requester_user_id: opts.requesterUserId,
  };
}

/** Extract a bearer token from an Authorization header value. */
export function bearerToken(header: string | null | undefined): string | null {
  if (!header) return null;
  const match = /^Bearer\s+(\S+)$/i.exec(header.trim());
  return match ? match[1] : null;
}
