
-- Add comprehensive automotive inventory categories
INSERT INTO inventory_categories (name) VALUES
-- Engine & Powertrain
('Engine Block Components'),
('Pistons & Rings'),
('Crankshaft & Connecting Rods'),
('Camshaft & Valve Train'),
('Cylinder Heads & Valves'),
('Engine Gaskets & Seals'),
('Oil System Components'),
('Cooling System Radiators'),
('Cooling System Hoses'),
('Cooling System Pumps'),
('Thermostats & Housing'),
('Radiator Caps & Expansion Tanks'),
('Transmission Fluid & Filters'),
('Manual Transmission Parts'),
('Automatic Transmission Parts'),
('CVT Components'),
('Clutch Assemblies'),
('Clutch Discs & Pressure Plates'),
('Flywheel & Flexplate'),
('Driveshaft Components'),
('CV Joints & Boots'),
('Differential Parts'),
('Transfer Case Components'),

-- Fuel System
('Fuel Pumps & Modules'),
('Fuel Injectors & Rails'),
('Fuel Filters'),
('Carburetor Components'),
('Throttle Bodies'),
('Fuel Lines & Fittings'),
('Gas Tank Components'),
('Fuel Pressure Regulators'),
('Mass Air Flow Sensors'),
('Oxygen Sensors'),
('Fuel Tank Sending Units'),

-- Exhaust System
('Exhaust Manifolds'),
('Catalytic Converters'),
('Mufflers & Resonators'),
('Exhaust Pipes & Tubing'),
('Exhaust Gaskets & Hardware'),
('Turbochargers'),
('Superchargers'),
('Intercoolers'),
('Exhaust Tips & Extensions'),
('Exhaust Clamps & Hangers'),
('DPF & SCR Components'),
('EGR Valves & Components'),

-- Electrical & Electronics
('Alternators & Starters'),
('Batteries & Terminals'),
('Ignition Coils'),
('Spark Plugs & Wires'),
('Distributors & Caps'),
('Electronic Control Modules'),
('Wiring Harnesses'),
('Fuses & Relays'),
('Sensors - Temperature'),
('Sensors - Pressure'),
('Sensors - Position'),
('Sensors - Speed'),
('Engine Management Sensors'),
('Transmission Sensors'),
('ABS/ESP Sensors'),
('Airbag System Components'),
('Instrument Cluster Components'),
('Switches & Controls'),
('Horn & Electrical Accessories'),

-- Ignition System
('Ignition Modules'),
('Ignition Timing Components'),
('Glow Plugs (Diesel)'),
('Ignition Lock Cylinders'),
('Ignition Wire Sets'),
('Distributor Components'),
('Electronic Ignition Systems'),

-- Braking System
('Brake Pads - Front'),
('Brake Pads - Rear'),
('Brake Rotors - Front'),
('Brake Rotors - Rear'),
('Brake Drums'),
('Brake Shoes'),
('Brake Calipers'),
('Brake Master Cylinders'),
('Brake Fluid & DOT Ratings'),
('Brake Lines & Hoses'),
('ABS Components'),
('Brake Boosters'),
('Parking Brake Components'),
('Brake Hardware Kits'),
('Brake Sensors'),

-- Suspension & Steering
('Shock Absorbers'),
('Struts & Assemblies'),
('Springs - Coil'),
('Springs - Leaf'),
('Control Arms'),
('Ball Joints'),
('Tie Rod Ends'),
('Steering Racks'),
('Power Steering Pumps'),
('Steering Columns'),
('Wheel Bearings'),
('Bushings & Mounts'),
('Sway Bar Components'),
('Air Suspension Components'),
('Steering Fluid & Additives'),

-- HVAC & Climate Control
('A/C Compressors'),
('A/C Condensers'),
('A/C Evaporators'),
('Heater Cores'),
('Blower Motors & Resistors'),
('A/C Expansion Valves'),
('A/C Driers & Accumulators'),
('Cabin Air Filters'),
('HVAC Controls & Switches'),
('Refrigerant & A/C Oil'),
('Heater Hoses'),
('Climate Control Sensors'),

-- Body & Exterior
('Headlights & Assemblies'),
('Taillights & Assemblies'),
('Turn Signal Components'),
('Mirrors & Components'),
('Door Handles & Locks'),
('Window Regulators'),
('Body Panels'),
('Bumpers & Components'),
('Grilles & Trim'),
('Weatherstripping & Seals'),
('Hood & Trunk Components'),
('Windshield Wipers'),
('Washer Pumps & Reservoirs'),

-- Interior Components
('Seat Components'),
('Dashboard Components'),
('Interior Trim'),
('Floor Mats & Carpets'),
('Window Controls'),
('Interior Lights'),
('Cup Holders & Consoles'),
('Interior Door Panels'),

-- Tires & Wheels
('Tires - All Season'),
('Tires - Summer Performance'),
('Tires - Winter/Snow'),
('Tires - Off-Road'),
('Wheel Rims - Steel'),
('Wheel Rims - Alloy'),
('Tire Pressure Monitoring'),
('Valve Stems & Caps'),
('Wheel Weights'),
('Tire Repair Kits'),

-- Filters & Maintenance
('Engine Air Filters'),
('Oil Filters'),
('Fuel Filters'),
('Transmission Filters'),
('Hydraulic Filters'),
('PCV Valves'),
('Breather Elements'),

-- Fluids & Chemicals
('Motor Oil - Conventional'),
('Motor Oil - Synthetic'),
('Motor Oil - High Mileage'),
('Transmission Fluid'),
('Differential Oil'),
('Brake Fluid'),
('Power Steering Fluid'),
('Coolant & Antifreeze'),
('Windshield Washer Fluid'),
('Penetrating Oil'),
('Thread Locker'),
('Gasket Makers & Sealers'),
('Cleaning Solvents'),
('Rust Preventatives'),

-- Tools & Equipment
('Hand Tools - Wrenches'),
('Hand Tools - Sockets'),
('Hand Tools - Screwdrivers'),
('Specialty Automotive Tools'),
('Diagnostic Equipment'),
('Lifting Equipment'),
('Air Tools'),
('Measuring Tools'),
('Safety Equipment'),

-- Hardware & Fasteners
('Bolts & Screws - Metric'),
('Bolts & Screws - Standard'),
('Nuts & Washers'),
('Clips & Retainers'),
('Gasket Materials'),
('O-Rings & Seals'),
('Electrical Connectors'),
('Vacuum Hoses'),
('Adhesives & Tapes'),

-- Performance & Racing
('Performance Air Intakes'),
('Performance Exhaust'),
('Turbo & Supercharger Kits'),
('Engine Tuning Components'),
('Suspension Upgrades'),
('Brake Upgrades'),
('Intercooler Upgrades'),
('Fuel System Upgrades'),

-- Heavy Duty & Commercial
('Heavy Duty Engine Parts'),
('Commercial Vehicle Brakes'),
('Fleet Maintenance Items'),
('Hydraulic Components'),
('Air Brake Systems'),
('Heavy Duty Suspension'),

-- Motorcycle & Powersports
('Motorcycle Engine Parts'),
('Motorcycle Brakes'),
('Motorcycle Suspension'),
('ATV Components'),
('Marine Engine Parts'),
('Small Engine Components')

ON CONFLICT (name) DO NOTHING;
