
import { CustomerFormValues } from "./customerSchema";

// Default values for the form - no sample data
export const defaultCustomerFormValues: CustomerFormValues = {
  first_name: "",
  last_name: "",
  email: "",
  phone: "",
  address: "",
  city: "",
  state: "",
  postal_code: "",
  country: "",
  company: "",
  business_type: "",
  business_industry: "",
  other_business_industry: "",
  tax_id: "",
  business_email: "",
  business_phone: "",
  preferred_payment_method: "",
  auto_billing: false,
  credit_terms: "",
  terms_agreed: false,
  is_fleet: false,
  fleet_company: "",
  fleet_manager: "",
  fleet_contact: "",
  preferred_service_type: "",
  notes: "",
  shop_id: "",
  preferred_technician_id: "",
  communication_preference: "",
  referral_source: "",
  referral_person_id: "",
  other_referral_details: "",
  household_id: "",
  create_new_household: false,
  new_household_name: "",
  household_relationship: "",
  vehicles: [],
  tags: [],
  segments: [],
};
