import { 
  LayoutDashboard,
  Users,
  Wrench,
  Receipt,
  FileText,
  Package,
  Calendar,
  MessageSquare,
  Settings,
  BarChart3,
  ClipboardList,
  Phone,
  Star,
  Bell,
  Cog,
  Shield,
  HelpCircle,
  ShoppingCart,
  Building2,
  Truck,
  UserCog,
  FileBarChart,
  Building,
  Store,
  Code,
  Heart,
  LucideIcon
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'LayoutDashboard': LayoutDashboard,
  'Users': Users,
  'Wrench': Wrench,
  'Receipt': Receipt,
  'FileText': FileText,
  'Package': Package,
  'Calendar': Calendar,
  'MessageSquare': MessageSquare,
  'Settings': Settings,
  'BarChart3': BarChart3,
  'ClipboardList': ClipboardList,
  'Phone': Phone,
  'Star': Star,
  'Bell': Bell,
  'Cog': Cog,
  'Shield': Shield,
  'HelpCircle': HelpCircle,
  'ShoppingCart': ShoppingCart,
  'Building2': Building2,
  'Truck': Truck,
  'UserCog': UserCog,
  'FileBarChart': FileBarChart,
  'Building': Building,
  'Store': Store,
  'Code': Code,
  'Heart': Heart,
};

export function getIconComponent(iconName: string): LucideIcon {
  return iconMap[iconName] || Package; // Default to Package icon if not found
}