import { 
  Car, 
  Droplets, 
  Target, 
  Anchor, 
  Fuel, 
  LucideIcon,
  ShoppingCart,
  User,
  Briefcase,
  Crosshair,
  Package,
  BarChart3,
  FileText,
  CreditCard,
  Calendar,
  Shield,
  ArrowRightLeft,
  ShoppingBag,
  Wrench,
  Truck,
  Users,
  Gauge,
  Receipt,
  Ship,
  MapPin,
  Droplet,
  Link,
  Beaker,
  DollarSign,
  Route,
  CloudSun,
  Camera,
  Star,
  UserPlus,
  Calculator,
  Repeat,
  ClipboardList,
  Bell,
  Globe,
  Activity,
  History,
  FileSearch,
  Compass,
  Snowflake,
  CircleDollarSign,
  Smartphone,
  Container,
  PackageCheck,
  UserCheck,
  FolderOpen,
  Tractor,
  Building,
  Scissors,
  Home,
  Leaf,
  Zap,
  Paintbrush,
  // Additional icons for upcoming modules
  Waves,
  Flame,
  ThermometerSun,
  Bug,
  TreeDeciduous,
  Hammer,
  Fence,
  Sparkles,
  Shirt,
  Dog,
  Heart,
  Baby,
  GraduationCap,
  Music,
  Dumbbell,
  UtensilsCrossed,
  Coffee,
  Beer,
  Wine,
  Cake,
  Pizza,
  IceCream,
  Flower2,
  Mountain,
  Tent,
  Bike,
  Plane,
  Bus,
  Train,
  Warehouse,
  Factory,
  HardHat,
  Drill,
  Axe,
  Shovel,
  Flashlight,
  Lock,
  Key,
  Video,
  Tv,
  Wifi,
  Server,
  Database,
  Code,
  Printer,
  ScanLine,
  Cog,
  Settings,
  Cpu,
  Monitor,
  Speaker,
  Headphones,
  Gamepad2,
  Watch,
  Glasses,
  Gem,
  Crown,
  Ribbon,
  Gift,
  PartyPopper,
  Palette,
  Frame,
  ImageIcon,
  Brush,
  PenTool,
  Type,
  BookOpen,
  Newspaper,
  FileSpreadsheet,
  FilePlus,
  FolderHeart,
  Archive,
  Box,
  Boxes,
  Armchair,
  Lamp,
  BedDouble,
  Bath,
  ShowerHead,
  Plug,
  Fan,
  AirVent,
  Wind,
  Sun,
  Moon,
  Umbrella,
  CloudRain,
  Footprints,
  Bone,
  Cat,
  Bird,
  Fish,
  Turtle,
  Stethoscope,
  Pill,
  Syringe,
  Microscope,
  TestTube,
  Atom,
  Rocket,
  Satellite,
  Radio,
  Antenna,
  Phone,
  PhoneCall,
  MessageSquare,
  Mail,
  Send,
  Inbox,
  Share2,
  Network,
  Workflow,
  GitBranch,
  Terminal,
  Binary,
  QrCode,
  Fingerprint,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  List,
  Grid3X3,
  LayoutDashboard,
  Columns,
  Rows,
  Table,
  PieChart,
  TrendingUp,
  LineChart,
  Award,
  Trophy,
  Medal,
  BadgeCheck,
  BadgeAlert,
  AlertTriangle,
  Info,
  HelpCircle,
  XCircle,
  CheckCircle,
  PlusCircle,
  MinusCircle,
  RefreshCw,
  RotateCcw,
  Undo,
  Redo,
  Copy,
  Clipboard,
  Trash2,
  Edit,
  PenLine,
  Highlighter,
  Eraser,
  Wand2,
  Sparkle,
  Lightbulb,
  Megaphone,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Heart as HeartIcon,
  Bookmark,
  Flag,
  Pin,
  Navigation,
  Move,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Fullscreen,
  SplitSquareVertical,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Heading1,
  Heading2,
  Heading3,
  ListOrdered,
  ListChecks,
  Quote,
  Code2,
  Braces,
  Terminal as TerminalIcon
} from 'lucide-react';

export interface ModuleSectionItem {
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  group?: string;
  isExternal?: boolean;
}

export interface ModuleRouteConfig {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  dashboardRoute: string;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  sections?: ModuleSectionItem[];
}

export interface UpcomingModuleConfig {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  gradientFrom: string;
  gradientTo: string;
  expectedDate?: string;
  category?: string;
}

export const UPCOMING_MODULES: UpcomingModuleConfig[] = [
  // Home & Property Services
  {
    slug: 'hvac',
    name: 'HVAC Services',
    description: 'Heating, cooling, and ventilation with EPA 608 compliance',
    icon: ThermometerSun,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'pool-spa',
    name: 'Pool & Spa Services',
    description: 'Chemical tracking, water testing, and route management',
    icon: Waves,
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'plumbing',
    name: 'Plumbing Services',
    description: 'Residential and commercial plumbing with parts inventory',
    icon: Wrench,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'electrical',
    name: 'Electrical Services',
    description: 'Electrical contracting with permit and inspection tracking',
    icon: Zap,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'roofing',
    name: 'Roofing',
    description: 'Roof inspections, repairs, and project management',
    icon: Home,
    gradientFrom: 'from-slate-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'painting',
    name: 'Painting Services',
    description: 'Interior/exterior painting with estimating and crew dispatch',
    icon: Paintbrush,
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'handyman',
    name: 'Handyman Services',
    description: 'Multi-trade repairs with flexible pricing and scheduling',
    icon: Hammer,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'fencing',
    name: 'Fencing',
    description: 'Fence installation, repair, and material estimating',
    icon: Fence,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'landscaping',
    name: 'Landscaping',
    description: 'Lawn care, design, irrigation, and crew scheduling',
    icon: Leaf,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'pest-control',
    name: 'Pest Control',
    description: 'Route optimization, chemical compliance, and treatment plans',
    icon: Bug,
    gradientFrom: 'from-lime-500',
    gradientTo: 'to-green-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  // septic removed - now a live module
  {
    slug: 'window-cleaning',
    name: 'Window Cleaning',
    description: 'Commercial and residential window and gutter cleaning',
    icon: Sparkles,
    gradientFrom: 'from-sky-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'carpet-cleaning',
    name: 'Carpet Cleaning',
    description: 'Deep cleaning, stain removal, and upholstery services',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'chimney-sweep',
    name: 'Chimney Sweep',
    description: 'Chimney cleaning, inspections, and fireplace services',
    icon: Flame,
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'garage-door',
    name: 'Garage Door Services',
    description: 'Installation, repair, and opener maintenance',
    icon: Home,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-gray-700',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'solar',
    name: 'Solar Installation',
    description: 'Panel installation, maintenance, and energy monitoring',
    icon: Sun,
    gradientFrom: 'from-yellow-400',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'insulation',
    name: 'Insulation Services',
    description: 'Spray foam, blown-in, and energy efficiency audits',
    icon: Home,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'flooring',
    name: 'Flooring',
    description: 'Hardwood, tile, carpet, and laminate installation',
    icon: Grid3X3,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'countertops',
    name: 'Countertop Installation',
    description: 'Granite, quartz, and solid surface fabrication',
    icon: Rows,
    gradientFrom: 'from-stone-400',
    gradientTo: 'to-stone-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'drywall',
    name: 'Drywall Services',
    description: 'Installation, finishing, and repair work',
    icon: Columns,
    gradientFrom: 'from-neutral-400',
    gradientTo: 'to-neutral-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'concrete',
    name: 'Concrete Services',
    description: 'Driveways, patios, foundations, and decorative concrete',
    icon: Box,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'masonry',
    name: 'Masonry',
    description: 'Brick, stone, and block work with restoration',
    icon: Boxes,
    gradientFrom: 'from-red-700',
    gradientTo: 'to-red-900',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },

  // Construction & Trade
  {
    slug: 'general-contractor',
    name: 'General Contractor',
    description: 'Full construction project management and subcontractor coordination',
    icon: HardHat,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'demolition',
    name: 'Demolition',
    description: 'Structural demolition and debris removal',
    icon: Hammer,
    gradientFrom: 'from-red-600',
    gradientTo: 'to-red-800',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'excavation',
    name: 'Excavation',
    description: 'Site prep, grading, and earthwork services',
    icon: Shovel,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'framing',
    name: 'Framing',
    description: 'Residential and commercial framing projects',
    icon: Building,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'siding',
    name: 'Siding Installation',
    description: 'Vinyl, wood, fiber cement, and metal siding',
    icon: Columns,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-blue-700',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'deck-building',
    name: 'Deck Building',
    description: 'Custom decks, pergolas, and outdoor structures',
    icon: TreeDeciduous,
    gradientFrom: 'from-amber-700',
    gradientTo: 'to-yellow-800',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'cabinet-making',
    name: 'Cabinet Making',
    description: 'Custom cabinetry and millwork',
    icon: Box,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Construction & Trade',
  },

  // Automotive & Transportation
  {
    slug: 'auto-detailing',
    name: 'Auto Detailing',
    description: 'Interior/exterior detailing and paint correction',
    icon: Sparkles,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'tire-shop',
    name: 'Tire Shop',
    description: 'Tire sales, mounting, balancing, and alignment',
    icon: Circle,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-gray-800',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'body-shop',
    name: 'Body Shop',
    description: 'Collision repair, paint, and insurance claims',
    icon: Car,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'towing',
    name: 'Towing Services',
    description: 'Roadside assistance and vehicle recovery',
    icon: Truck,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'motorcycle',
    name: 'Motorcycle Services',
    description: 'Motorcycle repair and customization',
    icon: Bike,
    gradientFrom: 'from-red-600',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'rv-services',
    name: 'RV Services',
    description: 'RV repair, maintenance, and winterization',
    icon: Bus,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-teal-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'auto-glass',
    name: 'Auto Glass',
    description: 'Windshield repair and replacement',
    icon: Car,
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'transmission',
    name: 'Transmission Shop',
    description: 'Transmission repair and rebuilds',
    icon: Cog,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-700',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'muffler-exhaust',
    name: 'Muffler & Exhaust',
    description: 'Exhaust systems and emissions repair',
    icon: Wind,
    gradientFrom: 'from-zinc-500',
    gradientTo: 'to-zinc-700',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },

  // Personal Services
  {
    slug: 'salon',
    name: 'Salon & Spa',
    description: 'Beauty salon and spa appointment management',
    icon: Scissors,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'barbershop',
    name: 'Barbershop',
    description: 'Barber appointments and client management',
    icon: Scissors,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-slate-700',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'nail-salon',
    name: 'Nail Salon',
    description: 'Manicure, pedicure, and nail art services',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-fuchsia-500',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'esthetician',
    name: 'Esthetician',
    description: 'Lashes, brows, facials, waxing, and skincare services',
    icon: Sparkles,
    gradientFrom: 'from-rose-400',
    gradientTo: 'to-pink-500',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'tattoo',
    name: 'Tattoo Studio',
    description: 'Tattoo appointments and portfolio management',
    icon: PenTool,
    gradientFrom: 'from-gray-700',
    gradientTo: 'to-black',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'massage',
    name: 'Massage Therapy',
    description: 'Massage bookings and treatment tracking',
    icon: Heart,
    gradientFrom: 'from-purple-400',
    gradientTo: 'to-violet-500',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'personal-training',
    name: 'Personal Training',
    description: 'Fitness coaching and client progress tracking',
    icon: Dumbbell,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'yoga-pilates',
    name: 'Yoga & Pilates Studio',
    description: 'Class scheduling and membership management',
    icon: Heart,
    gradientFrom: 'from-teal-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'photography',
    name: 'Photography',
    description: 'Photo shoots, editing, and client galleries',
    icon: Camera,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'videography',
    name: 'Videography',
    description: 'Video production and event filming',
    icon: Video,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'tutoring',
    name: 'Tutoring',
    description: 'Educational tutoring and lesson scheduling',
    icon: GraduationCap,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'music-lessons',
    name: 'Music Lessons',
    description: 'Music instruction and recital management',
    icon: Music,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q4 2026',
    category: 'Personal Services',
  },

  // Pet Services
  {
    slug: 'pet-grooming',
    name: 'Pet Grooming',
    description: 'Grooming appointments and pet profiles',
    icon: Dog,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Pet Services',
  },
  {
    slug: 'veterinary',
    name: 'Veterinary Clinic',
    description: 'Pet health records and appointment scheduling',
    icon: Stethoscope,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q2 2026',
    category: 'Pet Services',
  },
  {
    slug: 'pet-boarding',
    name: 'Pet Boarding',
    description: 'Boarding reservations and pet care tracking',
    icon: Home,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'dog-walking',
    name: 'Dog Walking',
    description: 'Walk scheduling and route tracking',
    icon: Footprints,
    gradientFrom: 'from-green-400',
    gradientTo: 'to-lime-500',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'pet-sitting',
    name: 'Pet Sitting',
    description: 'In-home pet care and daily updates',
    icon: Cat,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'dog-training',
    name: 'Dog Training',
    description: 'Training sessions and progress tracking',
    icon: Dog,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q4 2026',
    category: 'Pet Services',
  },

  // Food & Beverage
  {
    slug: 'catering',
    name: 'Catering',
    description: 'Event catering and menu planning',
    icon: UtensilsCrossed,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'food-truck',
    name: 'Food Truck',
    description: 'Mobile food service and location scheduling',
    icon: Truck,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'bakery',
    name: 'Bakery',
    description: 'Custom orders and production scheduling',
    icon: Cake,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'coffee-shop',
    name: 'Coffee Shop',
    description: 'Cafe operations and inventory management',
    icon: Coffee,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'brewery',
    name: 'Brewery',
    description: 'Brew tracking, taproom, and distribution',
    icon: Beer,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'winery',
    name: 'Winery',
    description: 'Wine production and tasting room management',
    icon: Wine,
    gradientFrom: 'from-red-700',
    gradientTo: 'to-purple-800',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },

  // Technology & Electronics
  {
    slug: 'computer-repair',
    name: 'Computer Repair',
    description: 'PC and laptop diagnostics and repair',
    icon: Monitor,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'phone-repair',
    name: 'Phone Repair',
    description: 'Smartphone and tablet repair services',
    icon: Smartphone,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'it-services',
    name: 'IT Services',
    description: 'Managed IT and network support',
    icon: Server,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'security-systems',
    name: 'Security Systems',
    description: 'Alarm, camera, and access control installation',
    icon: Lock,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'home-theater',
    name: 'Home Theater',
    description: 'Audio/video installation and smart home',
    icon: Tv,
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'appliance-repair',
    name: 'Appliance Repair',
    description: 'Major appliance diagnostics and repair',
    icon: Cog,
    gradientFrom: 'from-zinc-500',
    gradientTo: 'to-zinc-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },

  // Specialty & Niche
  {
    slug: 'locksmith',
    name: 'Locksmith',
    description: 'Lock installation, repair, and emergency services',
    icon: Key,
    gradientFrom: 'from-yellow-600',
    gradientTo: 'to-amber-700',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'moving',
    name: 'Moving Services',
    description: 'Residential and commercial moving',
    icon: Truck,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'storage',
    name: 'Storage Facilities',
    description: 'Unit rentals and access management',
    icon: Warehouse,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-600',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'junk-removal',
    name: 'Junk Removal',
    description: 'Hauling and disposal services',
    icon: Trash2,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'tree-service',
    name: 'Tree Service',
    description: 'Tree trimming, removal, and stump grinding',
    icon: TreeDeciduous,
    gradientFrom: 'from-green-700',
    gradientTo: 'to-green-900',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'irrigation',
    name: 'Irrigation',
    description: 'Sprinkler installation and repair',
    icon: Droplet,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'snow-removal',
    name: 'Snow Removal',
    description: 'Plowing, salting, and snow management',
    icon: Snowflake,
    gradientFrom: 'from-blue-300',
    gradientTo: 'to-cyan-400',
    expectedDate: 'Q4 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'event-planning',
    name: 'Event Planning',
    description: 'Event coordination and vendor management',
    icon: PartyPopper,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'dj-entertainment',
    name: 'DJ & Entertainment',
    description: 'Event booking and equipment tracking',
    icon: Music,
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-700',
    expectedDate: 'Q4 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'cleaning-residential',
    name: 'Residential Cleaning',
    description: 'House cleaning and maid services',
    icon: Sparkles,
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'cleaning-commercial',
    name: 'Commercial Cleaning',
    description: 'Janitorial and office cleaning',
    icon: Building,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'laundry',
    name: 'Laundry Services',
    description: 'Dry cleaning and laundry pickup/delivery',
    icon: Shirt,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },

  // Agriculture & Outdoor
  {
    slug: 'agriculture',
    name: 'Agriculture & Farm',
    description: 'Farm equipment service and agricultural operations',
    icon: Tractor,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'lawn-mower',
    name: 'Lawn Mower Repair',
    description: 'Small engine and mower maintenance',
    icon: Cog,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-lime-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'outdoor-power',
    name: 'Outdoor Power Equipment',
    description: 'Chainsaw, trimmer, and blower service',
    icon: Axe,
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'nursery',
    name: 'Plant Nursery',
    description: 'Plant inventory and sales management',
    icon: Flower2,
    gradientFrom: 'from-green-400',
    gradientTo: 'to-emerald-500',
    expectedDate: 'Q4 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'greenhouse',
    name: 'Greenhouse',
    description: 'Growing operations and climate control',
    icon: Leaf,
    gradientFrom: 'from-lime-500',
    gradientTo: 'to-green-600',
    expectedDate: 'Q4 2026',
    category: 'Agriculture & Outdoor',
  },

  // Professional Services
  {
    slug: 'consulting',
    name: 'Consulting',
    description: 'Client engagements and project tracking',
    icon: Briefcase,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'accounting',
    name: 'Accounting Firm',
    description: 'Client management and tax preparation',
    icon: Calculator,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'legal',
    name: 'Legal Services',
    description: 'Case management and billing',
    icon: FileText,
    gradientFrom: 'from-gray-700',
    gradientTo: 'to-slate-900',
    expectedDate: 'Q4 2026',
    category: 'Professional Services',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    description: 'Property listings and transaction management',
    icon: Home,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'property-management',
    name: 'Property Management',
    description: 'Rental properties and tenant management',
    icon: Building,
    gradientFrom: 'from-slate-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'insurance',
    name: 'Insurance Agency',
    description: 'Policy management and claims tracking',
    icon: Shield,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q4 2026',
    category: 'Professional Services',
  },

  // Healthcare & Wellness
  {
    slug: 'chiropractic',
    name: 'Chiropractic',
    description: 'Patient scheduling and treatment plans',
    icon: Activity,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-teal-600',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'dental',
    name: 'Dental Practice',
    description: 'Patient records and appointment management',
    icon: Sparkles,
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'physical-therapy',
    name: 'Physical Therapy',
    description: 'Therapy sessions and progress tracking',
    icon: Activity,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'optometry',
    name: 'Optometry',
    description: 'Eye exams and optical dispensing',
    icon: Eye,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q4 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'medical-spa',
    name: 'Medical Spa',
    description: 'Aesthetic treatments and consultations',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q4 2026',
    category: 'Healthcare & Wellness',
  },

  // Childcare & Education
  {
    slug: 'daycare',
    name: 'Daycare Center',
    description: 'Child enrollment and daily tracking',
    icon: Baby,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-purple-500',
    expectedDate: 'Q3 2026',
    category: 'Childcare & Education',
  },
  {
    slug: 'after-school',
    name: 'After School Program',
    description: 'Program registration and attendance',
    icon: GraduationCap,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q4 2026',
    category: 'Childcare & Education',
  },
  {
    slug: 'summer-camp',
    name: 'Summer Camp',
    description: 'Camp registration and activity planning',
    icon: Tent,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q4 2026',
    category: 'Childcare & Education',
  },

  // Recreation & Sports
  {
    slug: 'golf-course',
    name: 'Golf Course',
    description: 'Tee times and membership management',
    icon: Flag,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-lime-600',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'ski-snowboard',
    name: 'Ski & Snowboard',
    description: 'Equipment rentals and lessons',
    icon: Mountain,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'bike-shop',
    name: 'Bike Shop',
    description: 'Bicycle sales, repair, and rentals',
    icon: Bike,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'fishing-charter',
    name: 'Fishing Charter',
    description: 'Charter bookings and trip management',
    icon: Fish,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-cyan-700',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'hunting-guide',
    name: 'Hunting Guide',
    description: 'Hunt bookings and licensing compliance',
    icon: Target,
    gradientFrom: 'from-green-700',
    gradientTo: 'to-green-900',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },

  // Retail & Crafts
  {
    slug: 'jewelry',
    name: 'Jewelry Store',
    description: 'Custom orders and repair services',
    icon: Gem,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'watch-repair',
    name: 'Watch Repair',
    description: 'Watch servicing and parts tracking',
    icon: Watch,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'upholstery',
    name: 'Upholstery',
    description: 'Furniture reupholstering and fabric selection',
    icon: Armchair,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'tailor',
    name: 'Tailor & Alterations',
    description: 'Clothing alterations and custom tailoring',
    icon: Scissors,
    gradientFrom: 'from-indigo-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'picture-framing',
    name: 'Picture Framing',
    description: 'Custom framing and matting',
    icon: Frame,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'printing',
    name: 'Print Shop',
    description: 'Commercial printing and signage',
    icon: Printer,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
];

export const MODULE_ROUTES: Record<string, ModuleRouteConfig> = {
  automotive: {
    slug: 'automotive',
    name: 'Automotive Repair',
    description: 'Full-service auto repair shop management',
    icon: Car,
    dashboardRoute: '/automotive',
    color: 'hsl(var(--primary))',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-blue-600',
    sections: [
      // Dashboard
      { title: 'Dashboard', href: '/automotive', icon: Gauge, description: 'Module overview and KPIs', group: 'Dashboard' },
      
      // Services
      { title: 'All Jobs', href: '/work-orders', icon: Briefcase, description: 'Work orders and repairs', group: 'Services' },
      { title: 'Quotes', href: '/quotes', icon: FileText, description: 'Estimates and quotes', group: 'Services' },
      { title: 'Invoices', href: '/invoices', icon: Receipt, description: 'Billing and invoices', group: 'Services' },
      { title: 'Payments', href: '/payments', icon: CreditCard, description: 'Payment processing', group: 'Services' },
      { title: 'Service Packages', href: '/service-packages', icon: Package, description: 'Service bundles', group: 'Services' },
      
      // Customers
      { title: 'Customers', href: '/customers', icon: Users, description: 'Customer management', group: 'Customers' },
      { title: 'Vehicle History', href: '/automotive/vehicle-history', icon: History, description: 'Complete service history', group: 'Customers' },
      
      // Inventory
      { title: 'Parts', href: '/inventory', icon: Package, description: 'Parts inventory', group: 'Inventory' },
      { title: 'Parts Tracking', href: '/parts-tracking', icon: Package, description: 'Track parts orders', group: 'Inventory' },
      { title: 'Suppliers', href: '/inventory-suppliers', icon: Users, description: 'Vendor management', group: 'Inventory' },
      
      // Scheduling
      { title: 'Appointments', href: '/booking-management', icon: Calendar, description: 'Booking management', group: 'Scheduling' },
      { title: 'Planner', href: '/planner', icon: Calendar, description: 'Job planner', group: 'Scheduling' },
      { title: 'Calendar', href: '/calendar', icon: Calendar, description: 'Service calendar', group: 'Scheduling' },
      
      // Communications
      { title: 'Customer Comms', href: '/customer-comms', icon: Bell, description: 'Customer messaging', group: 'Communications' },
      { title: 'Call Logger', href: '/call-logger', icon: Bell, description: 'Call tracking', group: 'Communications' },
      
      // Marketing
      { title: 'Email Campaigns', href: '/email-campaigns', icon: Globe, description: 'Email marketing', group: 'Marketing' },
      { title: 'SMS Management', href: '/sms-management', icon: Smartphone, description: 'Text messaging', group: 'Marketing' },
      
      // Operations
      { title: 'Daily Logs', href: '/daily-logs', icon: ClipboardList, description: 'Daily operations', group: 'Operations' },
      { title: 'Service Board', href: '/service-board', icon: Briefcase, description: 'Live job board', group: 'Operations' },
      
      // Equipment & Tools
      { title: 'Equipment', href: '/equipment', icon: Wrench, description: 'Shop equipment', group: 'Equipment & Tools' },
      { title: 'Maintenance', href: '/maintenance-requests', icon: Wrench, description: 'Equipment maintenance', group: 'Equipment & Tools' },
      
      // Fleet
      { title: 'Vehicles', href: '/vehicles', icon: Car, description: 'Customer vehicles', group: 'Fleet' },
      { title: 'Fleet Management', href: '/fleet-management', icon: Truck, description: 'Fleet tracking', group: 'Fleet' },
      { title: 'Fuel Management', href: '/fuel-management', icon: Fuel, description: 'Fuel tracking', group: 'Fleet' },
      { title: 'Tire Management', href: '/tire-management', icon: Car, description: 'Tire tracking', group: 'Fleet' },
      
      // Safety & Compliance
      { title: 'Safety Dashboard', href: '/safety', icon: Shield, description: 'Safety overview', group: 'Safety & Compliance' },
      { title: 'DVIR', href: '/safety/dvir', icon: ClipboardList, description: 'Vehicle inspections', group: 'Safety & Compliance' },
      { title: 'Inspections', href: '/safety/inspections', icon: Shield, description: 'Safety inspections', group: 'Safety & Compliance' },
      
      // Company
      { title: 'Company Profile', href: '/company-profile', icon: Users, description: 'Business info', group: 'Company' },
      { title: 'Team', href: '/team', icon: Users, description: 'Staff management', group: 'Company' },
      { title: 'Settings', href: '/settings', icon: Wrench, description: 'Module settings', group: 'Company' },
      
      // Automotive-Specific
      { title: 'Diagnostics', href: '/automotive/diagnostics', icon: Activity, description: 'Diagnostic tools', group: 'Automotive' },
      { title: 'Labor Rates', href: '/automotive/labor-rates', icon: DollarSign, description: 'Rate management', group: 'Automotive' },
      { title: 'TSB & Recalls', href: '/automotive/recalls', icon: FileSearch, description: 'Technical bulletins', group: 'Automotive' },
      // Resources
      { title: 'Recommended Gear', href: '/automotive/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  power_washing: {
    slug: 'power_washing',
    name: 'Power Washing',
    description: 'Pressure washing business management',
    icon: Droplets,
    dashboardRoute: '/power-washing',
    color: 'hsl(var(--chart-2))',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-cyan-600',
    sections: [
      // Dashboard
      { title: 'Dashboard', href: '/power-washing', icon: Gauge, description: 'Module overview and KPIs', group: 'Dashboard' },
      // Services
      { title: 'All Jobs', href: '/power-washing/jobs', icon: Briefcase, description: 'Job management', group: 'Services' },
      { title: 'Quotes', href: '/power-washing/quotes', icon: FileText, description: 'Estimates and quotes', group: 'Services' },
      { title: 'Schedule', href: '/power-washing/schedule', icon: Calendar, description: 'Job scheduling', group: 'Services' },
      { title: 'Routes', href: '/power-washing/routes', icon: Route, description: 'Route optimization', group: 'Services' },
      { title: 'Recurring', href: '/power-washing/recurring', icon: Repeat, description: 'Recurring schedules', group: 'Services' },
      // Customers
      { title: 'Customers', href: '/power-washing/customers', icon: Users, description: 'Customer management', group: 'Customers' },
      { title: 'Leads', href: '/power-washing/leads', icon: UserPlus, description: 'Lead management', group: 'Customers' },
      { title: 'Reviews', href: '/power-washing/reviews', icon: Star, description: 'Customer reviews', group: 'Customers' },
      { title: 'Subscriptions', href: '/power-washing/subscriptions', icon: CreditCard, description: 'Subscription plans', group: 'Customers' },
      // Billing
      { title: 'Invoices', href: '/power-washing/invoices', icon: Receipt, description: 'Billing and invoices', group: 'Billing' },
      { title: 'Payments', href: '/power-washing/payments', icon: CreditCard, description: 'Payment processing', group: 'Billing' },
      { title: 'Price Book', href: '/power-washing/price-book', icon: DollarSign, description: 'Service pricing', group: 'Billing' },
      // Operations
      { title: 'Equipment', href: '/power-washing/equipment', icon: Wrench, description: 'Equipment management', group: 'Operations' },
      { title: 'Fleet', href: '/power-washing/fleet', icon: Truck, description: 'Vehicle fleet', group: 'Operations' },
      { title: 'Inventory', href: '/power-washing/inventory', icon: Package, description: 'Supplies, parts & chemicals', group: 'Operations' },
      { title: 'Formulas', href: '/power-washing/formulas', icon: Calculator, description: 'Mix ratios and formulas', group: 'Operations' },
      // Tools
      { title: 'Weather', href: '/power-washing/weather', icon: CloudSun, description: 'Weather forecasts', group: 'Tools' },
      { title: 'Photos', href: '/power-washing/photos', icon: Camera, description: 'Before/after photos', group: 'Tools' },
      { title: 'Reports', href: '/power-washing/reports', icon: BarChart3, description: 'Analytics and reports', group: 'Tools' },
      { title: 'Field View', href: '/power-washing/field-view', icon: Smartphone, description: 'Mobile field app', group: 'Tools' },
      // Resources
      { title: 'Recommended Gear', href: '/power-washing/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      { title: 'Customer Portal', href: '/power-washing/portal', icon: Globe, description: 'Customer self-service', group: 'Resources' },
      // Settings
      { title: 'Settings', href: '/power-washing/settings', icon: Settings, description: 'Module configuration', group: 'Settings' },
      { title: 'Team', href: '/power-washing/team', icon: Users, description: 'Team management', group: 'Settings' },
      { title: 'Roles', href: '/power-washing/roles', icon: Shield, description: 'Role permissions', group: 'Settings' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  gunsmith: {
    slug: 'gunsmith',
    name: 'Gunsmith',
    description: 'Firearms service and compliance tracking',
    icon: Target,
    dashboardRoute: '/gunsmith',
    color: 'hsl(var(--chart-4))',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-amber-600',
    sections: [
      // Dashboard
      { title: 'Dashboard', href: '/gunsmith', icon: Gauge, group: 'Dashboard' },
      // Services
      { title: 'All Jobs', href: '/gunsmith/jobs', icon: Briefcase, group: 'Services' },
      { title: 'Quotes', href: '/gunsmith/quotes', icon: FileText, group: 'Services' },
      { title: 'Appointments', href: '/gunsmith/appointments', icon: Calendar, group: 'Services' },
      // Customers
      { title: 'Customers', href: '/gunsmith/customers', icon: Users, group: 'Customers' },
      { title: 'Firearms', href: '/gunsmith/firearms', icon: Crosshair, group: 'Customers' },
      // Inventory
      { title: 'Parts', href: '/gunsmith/parts', icon: Package, group: 'Inventory' },
      { title: 'Parts on Order', href: '/gunsmith/parts-on-order', icon: ShoppingBag, group: 'Inventory' },
      { title: 'Inventory', href: '/gunsmith/inventory', icon: BarChart3, group: 'Inventory' },
      // Billing
      { title: 'Invoices', href: '/gunsmith/invoices', icon: Receipt, group: 'Billing' },
      { title: 'Payments', href: '/gunsmith/payments', icon: CreditCard, group: 'Billing' },
      // Compliance
      { title: 'Compliance', href: '/gunsmith/compliance', icon: Shield, group: 'Compliance' },
      { title: 'Transfers', href: '/gunsmith/transfers', icon: ArrowRightLeft, group: 'Compliance' },
      { title: 'Consignments', href: '/gunsmith/consignments', icon: ShoppingBag, group: 'Compliance' },
      // Resources
      { title: 'Resources', href: '/gunsmith/resources', icon: Link, group: 'Resources' },
      { title: 'Feedback Log', href: '/gunsmith/change-log', icon: ClipboardList, group: 'Resources' },
      { title: 'Recommended Gear', href: '/gunsmith/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Settings
      { title: 'Settings', href: '/gunsmith/settings', icon: Settings, group: 'Settings' },
      { title: 'Team', href: '/gunsmith/team', icon: Users, group: 'Settings' },
      { title: 'Roles', href: '/gunsmith/roles', icon: Shield, group: 'Settings' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  marine: {
    slug: 'marine',
    name: 'Marine Services',
    description: 'Boat and watercraft maintenance',
    icon: Anchor,
    dashboardRoute: '/marine-services',
    color: 'hsl(var(--chart-3))',
    gradientFrom: 'from-teal-500',
    gradientTo: 'to-teal-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/marine-services', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'All Jobs', href: '/marine-services/jobs', icon: Briefcase, description: 'Work orders' },
      { title: 'Vessels', href: '/marine-services/vessels', icon: Ship, description: 'Vessel registry' },
      { title: 'Parts', href: '/marine-services/parts', icon: Package, description: 'Parts inventory' },
      { title: 'Quotes', href: '/marine-services/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/marine-services/invoices', icon: Receipt, description: 'Billing and invoices' },
      { title: 'Payments', href: '/marine-services/payments', icon: CreditCard, description: 'Payment processing' },
      { title: 'Dock Schedule', href: '/marine-services/schedule', icon: Calendar, description: 'Dock scheduling' },
      // Marine-Specific Features
      { title: 'Sea Trials', href: '/marine-services/sea-trials', icon: Compass, description: 'Sea trial scheduling and logs' },
      { title: 'Haul-Outs', href: '/marine-services/haul-outs', icon: Anchor, description: 'Haul-out scheduling' },
      { title: 'Winterization', href: '/marine-services/winterization', icon: Snowflake, description: 'Winterization tracking' },
      { title: 'Compliance', href: '/marine-services/compliance', icon: Shield, description: 'Coast Guard compliance' },
      // Resources
      { title: 'Recommended Gear', href: '/marine-services/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  fuel_delivery: {
    slug: 'fuel_delivery',
    name: 'Fuel Delivery',
    description: 'Fuel delivery and tank management',
    icon: Fuel,
    dashboardRoute: '/fuel-delivery',
    color: 'hsl(var(--chart-5))',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-orange-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/fuel-delivery', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Orders', href: '/fuel-delivery/orders', icon: ClipboardList, description: 'Delivery orders' },
      { title: 'Customers', href: '/fuel-delivery/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/fuel-delivery/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/fuel-delivery/invoices', icon: Receipt, description: 'Billing and invoices' },
      // Tank Management
      { title: 'Tanks', href: '/fuel-delivery/tanks', icon: Container, description: 'Tank registry' },
      { title: 'Tidy Tanks', href: '/fuel-delivery/tidy-tanks', icon: PackageCheck, description: 'Tank maintenance' },
      { title: 'Tank Fills', href: '/fuel-delivery/tank-fills', icon: Droplet, description: 'Fill history' },
      { title: 'Locations', href: '/fuel-delivery/locations', icon: MapPin, description: 'Delivery locations' },
      // Fleet & Delivery
      { title: 'Routes', href: '/fuel-delivery/routes', icon: Route, description: 'Route optimization' },
      { title: 'Trucks', href: '/fuel-delivery/trucks', icon: Truck, description: 'Delivery trucks' },
      { title: 'Drivers', href: '/fuel-delivery/drivers', icon: UserCheck, description: 'Driver management' },
      { title: 'Equipment', href: '/fuel-delivery/equipment', icon: Wrench, description: 'Equipment tracking' },
      { title: 'Completions', href: '/fuel-delivery/completions', icon: FolderOpen, description: 'Completed deliveries' },
      // Products & Pricing
      { title: 'Products', href: '/fuel-delivery/products', icon: Fuel, description: 'Fuel products' },
      { title: 'Pricing', href: '/fuel-delivery/pricing', icon: CircleDollarSign, description: 'Price management' },
      { title: 'Inventory', href: '/fuel-delivery/inventory', icon: BarChart3, description: 'Fuel inventory' },
      // Mobile
      { title: 'Driver App', href: '/fuel-delivery/driver-app', icon: Smartphone, description: 'Mobile driver app' },
      // Resources
      { title: 'Recommended Gear', href: '/fuel-delivery/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  water_delivery: {
    slug: 'water_delivery',
    name: 'Water Delivery',
    description: 'Water delivery, tank management, and route optimization',
    icon: Droplet,
    dashboardRoute: '/water-delivery',
    color: 'hsl(var(--chart-1))',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/water-delivery', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Orders', href: '/water-delivery/orders', icon: ClipboardList, description: 'Delivery orders' },
      { title: 'Customers', href: '/water-delivery/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/water-delivery/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/water-delivery/invoices', icon: Receipt, description: 'Billing and invoices' },
      // Tank Management
      { title: 'Tanks', href: '/water-delivery/tanks', icon: Container, description: 'Tank registry' },
      { title: 'Tidy Tanks', href: '/water-delivery/tidy-tanks', icon: PackageCheck, description: 'Tank maintenance' },
      { title: 'Tank Fills', href: '/water-delivery/tank-fills', icon: Droplet, description: 'Fill history' },
      { title: 'Locations', href: '/water-delivery/locations', icon: MapPin, description: 'Delivery locations' },
      // Fleet & Delivery
      { title: 'Routes', href: '/water-delivery/routes', icon: Route, description: 'Route optimization' },
      { title: 'Trucks', href: '/water-delivery/trucks', icon: Truck, description: 'Water trucks' },
      { title: 'Drivers', href: '/water-delivery/drivers', icon: UserCheck, description: 'Driver management' },
      { title: 'Equipment', href: '/water-delivery/equipment', icon: Wrench, description: 'Equipment tracking' },
      { title: 'Equipment Filters', href: '/water-delivery/equipment-filters', icon: Filter, description: 'Filter maintenance' },
      { title: 'Deliveries', href: '/water-delivery/deliveries', icon: FolderOpen, description: 'Completed deliveries' },
      // Products & Pricing
      { title: 'Products', href: '/water-delivery/products', icon: Droplet, description: 'Water products' },
      { title: 'Pricing', href: '/water-delivery/pricing', icon: CircleDollarSign, description: 'Price management' },
      { title: 'Inventory', href: '/water-delivery/inventory', icon: BarChart3, description: 'Water inventory' },
      { title: 'Purchases', href: '/water-delivery/purchases', icon: ShoppingCart, description: 'Purchase orders' },
      // Mobile
      { title: 'Driver App', href: '/water-delivery/driver-app', icon: Smartphone, description: 'Mobile driver app' },
      // Settings
      { title: 'Profile', href: '/water-delivery/profile', icon: User, description: 'Module profile' },
      { title: 'Settings', href: '/water-delivery/settings', icon: Settings, description: 'Module settings' },
      // Resources
      { title: 'Recommended Gear', href: '/water-delivery/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  septic: {
    slug: 'septic',
    name: 'Septic Services',
    description: 'Septic pumping, inspections, and compliance tracking',
    icon: Container,
    dashboardRoute: '/septic',
    color: 'hsl(var(--chart-4))',
    gradientFrom: 'from-stone-500',
    gradientTo: 'to-stone-700',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/septic', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Service Orders', href: '/septic/orders', icon: ClipboardList, description: 'Pumping and service orders' },
      { title: 'Customers', href: '/septic/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/septic/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/septic/invoices', icon: Receipt, description: 'Billing and invoices' },
      // Tank Management
      { title: 'Septic Tanks', href: '/septic/tanks', icon: Container, description: 'Tank registry' },
      { title: 'System Components', href: '/septic/tidy-tanks', icon: PackageCheck, description: 'Baffles, risers, D-boxes' },
      { title: 'Pump-Outs', href: '/septic/tank-fills', icon: Droplet, description: 'Pump-out history' },
      { title: 'Locations', href: '/septic/locations', icon: MapPin, description: 'Service locations' },
      // Fleet & Delivery
      { title: 'Routes', href: '/septic/routes', icon: Route, description: 'Route optimization' },
      { title: 'Pump Trucks', href: '/septic/trucks', icon: Truck, description: 'Pump trucks' },
      { title: 'Drivers', href: '/septic/drivers', icon: UserCheck, description: 'Driver management' },
      { title: 'Equipment', href: '/septic/equipment', icon: Wrench, description: 'Equipment tracking' },
      { title: 'Completions', href: '/septic/completions', icon: FolderOpen, description: 'Completed services' },
      // Compliance
      { title: 'Inspections', href: '/septic/inspections', icon: Shield, description: 'EPA/county compliance' },
      // Products & Pricing
      { title: 'Products', href: '/septic/products', icon: Container, description: 'Service products' },
      { title: 'Pricing', href: '/septic/pricing', icon: CircleDollarSign, description: 'Price management' },
      { title: 'Inventory', href: '/septic/inventory', icon: BarChart3, description: 'Parts inventory' },
      { title: 'Purchases', href: '/septic/purchases', icon: ShoppingCart, description: 'Purchase orders' },
      // Mobile
      { title: 'Driver App', href: '/septic/driver-app', icon: Smartphone, description: 'Mobile driver app' },
      // Settings
      { title: 'Profile', href: '/septic/profile', icon: User, description: 'Module profile' },
      { title: 'Settings', href: '/septic/settings', icon: Settings, description: 'Module settings' },
      // Resources
      { title: 'Recommended Gear', href: '/septic/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      // Quick Links
      { title: 'Shop on Amazon', href: 'https://amzn.to/4b7nheJ', icon: ShoppingCart, description: 'Find more equipment on Amazon', group: 'Quick Links', isExternal: true },
    ],
  },
  'export-company': {
    slug: 'export-company',
    name: 'Export Company',
    description: 'Vehicle export operations, logistics, and compliance',
    icon: Ship,
    dashboardRoute: '/export',
    color: 'hsl(160, 60%, 40%)',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-teal-600',
    sections: [
      { title: 'Dashboard', href: '/export', icon: Gauge, description: 'Module overview and KPIs', group: 'Dashboard' },
      { title: 'KPI Dashboard', href: '/export/kpi-dashboard', icon: BarChart3, description: 'Key performance indicators', group: 'Dashboard' },
      // Services
      { title: 'Orders', href: '/export/orders', icon: ClipboardList, description: 'Export orders', group: 'Services' },
      { title: 'Customers', href: '/export/customers', icon: Users, description: 'Customer management', group: 'Services' },
      { title: 'Products', href: '/export/products', icon: Package, description: 'Product catalog', group: 'Services' },
      { title: 'Vehicles', href: '/export/vehicles', icon: Car, description: 'Vehicle inventory & VIN tracking', group: 'Services' },
      { title: 'Quotes', href: '/export/quotes', icon: FileText, description: 'Price quotes', group: 'Services' },
      { title: 'Requests', href: '/export/requests', icon: ClipboardList, description: 'Customer requests', group: 'Services' },
      { title: 'Samples', href: '/export/samples', icon: Package, description: 'Sample management', group: 'Services' },
      { title: 'Bookings', href: '/export/bookings', icon: Calendar, description: 'Booking management', group: 'Services' },
      { title: 'Contracts', href: '/export/contracts', icon: FileText, description: 'Contract management', group: 'Services' },
      // Logistics
      { title: 'Packaging', href: '/export/packaging', icon: Package, description: 'Packaging options & costs', group: 'Logistics' },
      { title: 'Shipments', href: '/export/shipments', icon: Ship, description: 'Shipment tracking', group: 'Logistics' },
      { title: 'Shipment Tracker', href: '/export/shipment-tracker', icon: MapPin, description: 'Real-time tracking', group: 'Logistics' },
      { title: 'Intermodal', href: '/export/intermodal', icon: Truck, description: 'Multi-leg transport', group: 'Logistics' },
      { title: 'Warehouses', href: '/export/warehouses', icon: Warehouse, description: 'Warehouse management', group: 'Logistics' },
      { title: 'Bonded Warehouses', href: '/export/bonded-warehouses', icon: Warehouse, description: 'FTZ & bonded facilities', group: 'Logistics' },
      { title: 'Ports', href: '/export/ports', icon: Anchor, description: 'Port & terminal directory', group: 'Logistics' },
      { title: 'Container Load Planning', href: '/export/container-load-planning', icon: Container, description: 'Container optimization', group: 'Logistics' },
      { title: 'Inventory', href: '/export/inventory', icon: PackageCheck, description: 'Stock management', group: 'Logistics' },
      { title: 'Packing Traceability', href: '/export/packing-traceability', icon: PackageCheck, description: 'Packing & tracing', group: 'Logistics' },
      { title: 'Shipping Insurance', href: '/export/shipping-insurance', icon: Shield, description: 'Cargo insurance', group: 'Logistics' },
      { title: 'Freight Forwarders', href: '/export/freight-forwarders', icon: Ship, description: '3PL management', group: 'Logistics' },
      // Documents & Compliance
      { title: 'Documents', href: '/export/documents', icon: FolderOpen, description: 'Export documents & customs', group: 'Documents' },
      { title: 'Document Templates', href: '/export/document-templates', icon: FileText, description: 'Template generation', group: 'Documents' },
      { title: 'Customs Declarations', href: '/export/customs-declarations', icon: FileText, description: 'AES/EEI filings', group: 'Documents' },
      { title: 'Certificates', href: '/export/certificates', icon: Award, description: 'Export certificates', group: 'Documents' },
      { title: 'HS Codes', href: '/export/hs-codes', icon: FileSearch, description: 'Tariff classification', group: 'Documents' },
      { title: 'Country Requirements', href: '/export/country-requirements', icon: Globe, description: 'Import regulations', group: 'Documents' },
      { title: 'Customs Compliance', href: '/export/customs-compliance', icon: Shield, description: 'Compliance center', group: 'Documents' },
      { title: 'Sanctions Screening', href: '/export/sanctions-screening', icon: Shield, description: 'OFAC/EU/UN screening', group: 'Documents' },
      { title: 'Compliance Calendar', href: '/export/compliance-calendar', icon: Calendar, description: 'Regulatory calendar', group: 'Documents' },
      // Fleet
      { title: 'Trucks', href: '/export/trucks', icon: Truck, description: 'Fleet trucks', group: 'Fleet' },
      { title: 'Drivers', href: '/export/drivers', icon: UserCheck, description: 'Driver management', group: 'Fleet' },
      { title: 'Routes', href: '/export/routes', icon: Route, description: 'Route planning', group: 'Fleet' },
      { title: 'Completions', href: '/export/completions', icon: PackageCheck, description: 'Delivery completions', group: 'Fleet' },
      { title: 'Driver App', href: '/export/driver-app', icon: Smartphone, description: 'Mobile driver app', group: 'Fleet' },
      // Billing & Finance
      { title: 'Invoices', href: '/export/invoices', icon: Receipt, description: 'Billing and invoices', group: 'Billing' },
      { title: 'Payments', href: '/export/payments', icon: CreditCard, description: 'Payment processing', group: 'Billing' },
      { title: 'Pricing', href: '/export/pricing', icon: DollarSign, description: 'Pricing configuration', group: 'Billing' },
      { title: 'Credit Management', href: '/export/credit-management', icon: CreditCard, description: 'Customer credit', group: 'Billing' },
      { title: 'Currency Rates', href: '/export/currency-rates', icon: DollarSign, description: 'Exchange rates', group: 'Billing' },
      { title: 'Letters of Credit', href: '/export/letters-of-credit', icon: FileText, description: 'LC lifecycle', group: 'Billing' },
      { title: 'Bank Guarantees', href: '/export/bank-guarantees', icon: Shield, description: 'Bank guarantees', group: 'Billing' },
      { title: 'Duty Drawbacks', href: '/export/duty-drawbacks', icon: DollarSign, description: 'Tax refunds', group: 'Billing' },
      // Intelligence & Analytics
      { title: 'Trade Finance', href: '/export/trade-finance', icon: DollarSign, description: 'Trade finance dashboard', group: 'Intelligence' },
      { title: 'Shipment P&L', href: '/export/shipment-pl', icon: BarChart3, description: 'Shipment profitability', group: 'Intelligence' },
      { title: 'Consolidated P&L', href: '/export/consolidated-pl', icon: BarChart3, description: 'Multi-currency P&L', group: 'Intelligence' },
      { title: 'Aging Reports', href: '/export/aging-reports', icon: BarChart3, description: 'AR/AP aging', group: 'Intelligence' },
      { title: 'Landed Cost Calculator', href: '/export/landed-cost-calculator', icon: Calculator, description: 'Cost analysis', group: 'Intelligence' },
      { title: 'Vendor Scorecards', href: '/export/vendor-scorecards', icon: Award, description: 'Supplier performance', group: 'Intelligence' },
      { title: 'Demand Forecasting', href: '/export/demand-forecasting', icon: TrendingUp, description: 'Demand predictions', group: 'Intelligence' },
      { title: 'Trade Lane Analytics', href: '/export/trade-lane-analytics', icon: Globe, description: 'Corridor analytics', group: 'Intelligence' },
      { title: 'Reports', href: '/export/reports', icon: BarChart3, description: 'Export reports', group: 'Intelligence' },
      // Procurement
      { title: 'Suppliers', href: '/export/suppliers', icon: Users, description: 'Supplier management', group: 'Procurement' },
      { title: 'Purchase Orders', href: '/export/import/purchase-orders', icon: ClipboardList, description: 'Import POs', group: 'Procurement' },
      { title: 'Receiving', href: '/export/import/receiving', icon: PackageCheck, description: 'Goods receiving', group: 'Procurement' },
      { title: 'Import Invoices', href: '/export/import/invoices', icon: Receipt, description: 'Import invoices', group: 'Procurement' },
      { title: 'Customs Clearance', href: '/export/import/customs-clearance', icon: Shield, description: 'Import clearance', group: 'Procurement' },
      // Quality & Returns
      { title: 'Quality Control', href: '/export/quality-control', icon: Shield, description: 'QC inspections', group: 'Quality' },
      { title: 'Returns & Claims', href: '/export/returns', icon: ArrowRightLeft, description: 'Returns management', group: 'Quality' },
      // Communications
      { title: 'Trade Alerts', href: '/export/trade-alerts', icon: Bell, description: 'Trade notifications', group: 'Communications' },
      { title: 'Messaging Templates', href: '/export/messaging-templates', icon: MessageSquare, description: 'Email/WhatsApp templates', group: 'Communications' },
      { title: 'Customer Portal', href: '/export/customer-portal', icon: Globe, description: 'Client self-service', group: 'Communications' },
      { title: 'Notifications', href: '/export/notifications', icon: Bell, description: 'System notifications', group: 'Communications' },
      // Integration
      { title: 'EDI Hub', href: '/export/edi-hub', icon: Code, description: 'EDI/API connections', group: 'Integration' },
      { title: 'Agents', href: '/export/agents', icon: Users, description: 'Agent management', group: 'Integration' },
      { title: 'Reservations', href: '/export/reservations', icon: Calendar, description: 'Space reservations', group: 'Integration' },
      // Settings
      { title: 'Staff', href: '/export/staff', icon: Users, description: 'Staff management', group: 'Settings' },
      { title: 'Equipment', href: '/export/equipment', icon: Wrench, description: 'Equipment tracking', group: 'Settings' },
      { title: 'Profile', href: '/export/profile', icon: User, description: 'Module profile', group: 'Settings' },
      { title: 'Settings', href: '/export/settings', icon: Settings, description: 'Module settings', group: 'Settings' },
      { title: 'Activity Log', href: '/export/activity-log', icon: ClipboardList, description: 'Audit trail', group: 'Settings' },
      // Resources
      { title: 'Recommended Gear', href: '/export/store', icon: ShoppingBag, description: 'Shop recommended equipment', group: 'Resources' },
      { title: 'Developer', href: '/export/developer', icon: Code, description: 'API & developer tools', group: 'Resources' },
    ],
  },
  personal_trainer: {
    slug: 'personal_trainer',
    name: 'Personal Trainer',
    description: 'Client management, workout programming, and session scheduling',
    icon: Dumbbell,
    dashboardRoute: '/personal-trainer',
    color: 'hsl(var(--chart-2))',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-600',
    sections: [
      { title: 'Dashboard', href: '/personal-trainer', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Clients', href: '/personal-trainer/clients', icon: Users, description: 'Client management' },
      { title: 'Workout Programs', href: '/personal-trainer/programs', icon: ClipboardList, description: 'Training programs' },
      { title: 'Exercises', href: '/personal-trainer/exercises', icon: Target, description: 'Exercise library' },
      { title: 'Sessions', href: '/personal-trainer/sessions', icon: Calendar, description: 'Session scheduling' },
      { title: 'Body Metrics', href: '/personal-trainer/metrics', icon: Activity, description: 'Progress tracking' },
      { title: 'Packages', href: '/personal-trainer/packages', icon: Package, description: 'Session packages', group: 'Billing' },
      { title: 'Client Billing', href: '/personal-trainer/billing', icon: CreditCard, description: 'Billing management', group: 'Billing' },
      { title: 'Settings', href: '/personal-trainer/settings', icon: Settings, description: 'Module settings' },
    ],
  },
  welding: {
    slug: 'welding',
    name: 'Welding & Fabrication',
    description: 'Complete welding and fabrication business management',
    icon: Flame,
    dashboardRoute: '/welding',
    color: 'hsl(var(--chart-4))',
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-700',
    sections: [
      { title: 'Dashboard', href: '/welding', icon: BarChart3, description: 'Module overview', group: 'Dashboard' },
      { title: 'Gallery', href: '/welding/gallery', icon: ImageIcon, description: 'Portfolio gallery', group: 'Services' },
      { title: 'Quotes', href: '/welding/quotes', icon: FileText, description: 'Quote management', group: 'Services' },
      { title: 'Invoices', href: '/welding/invoices', icon: Receipt, description: 'Invoice management', group: 'Billing' },
      { title: 'Payments Due', href: '/welding/payments-due', icon: DollarSign, description: 'Outstanding payments', group: 'Billing' },
      { title: 'Accounts Payable', href: '/welding/accounts-payable', icon: CreditCard, description: 'Bills & AP', group: 'Billing' },
      { title: 'Inventory', href: '/welding/inventory', icon: Package, description: 'Materials stock', group: 'Inventory' },
      { title: 'Purchase Orders', href: '/welding/purchase-orders', icon: ShoppingCart, description: 'PO tracking', group: 'Inventory' },
      { title: 'Customers', href: '/welding/customers', icon: Users, description: 'Customer CRM', group: 'Customers' },
      { title: 'Messages', href: '/welding/messages', icon: MessageSquare, description: 'Contact messages', group: 'Customers' },
      { title: 'Calendar', href: '/welding/calendar', icon: Calendar, description: 'Scheduling', group: 'Resources' },
      { title: 'Sales', href: '/welding/sales', icon: TrendingUp, description: 'Sales pipeline', group: 'Resources' },
      { title: 'Links', href: '/welding/links', icon: Link, description: 'External links', group: 'Resources' },
      { title: 'Settings', href: '/welding/settings', icon: Settings, description: 'Module settings' },
    ],
  },
  'game-development': {
    slug: 'game-development',
    name: 'Game Development',
    description: 'Complete game design planning and production management',
    icon: Gamepad2,
    dashboardRoute: '/game-development',
    color: 'hsl(var(--chart-3))',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-indigo-700',
    sections: [
      { title: 'Dashboard', href: '/game-development', icon: Gauge, description: 'Module overview', group: 'Dashboard' },
      { title: 'Projects', href: '/game-development/projects', icon: FolderOpen, description: 'Game projects', group: 'Planning' },
      { title: 'Canvas Planner', href: '/game-development/canvas', icon: LayoutDashboard, description: 'Visual planning boards', group: 'Planning' },
      { title: 'Database', href: '/game-development/database', icon: Database, description: 'Planning database', group: 'Planning' },
      { title: 'Roadmap', href: '/game-development/roadmap', icon: Route, description: 'Project roadmap', group: 'Planning' },
      { title: 'GDD Builder', href: '/game-development/gdd', icon: FileText, description: 'Game design documents', group: 'Planning' },
      { title: 'Story Tracker', href: '/game-development/story', icon: BookOpen, description: 'Narrative design', group: 'Narrative' },
      { title: 'Characters', href: '/game-development/characters', icon: Users, description: 'Character development', group: 'Narrative' },
      { title: 'Dialogue Trees', href: '/game-development/dialogue', icon: MessageSquare, description: 'Dialogue editor', group: 'Narrative' },
      { title: 'Wiki / Lore', href: '/game-development/wiki', icon: BookOpen, description: 'World lore wiki', group: 'Narrative' },
      { title: 'Items & Loot', href: '/game-development/items', icon: Package, description: 'Item database', group: 'Systems' },
      { title: 'Economy', href: '/game-development/economy', icon: TrendingUp, description: 'Economy simulation', group: 'Systems' },
      { title: 'Quests', href: '/game-development/quests', icon: Target, description: 'Quest designer', group: 'Systems' },
      { title: 'Raids & Events', href: '/game-development/raids', icon: Shield, description: 'Raids & events', group: 'Systems' },
      { title: 'Level Editor', href: '/game-development/levels', icon: Grid3X3, description: 'Zone & level editor', group: 'Systems' },
      { title: 'Playtest Journal', href: '/game-development/playtest', icon: ClipboardList, description: 'Playtest sessions', group: 'QA' },
      { title: 'Asset Requirements', href: '/game-development/assets', icon: ImageIcon, description: 'Asset tracking', group: 'Production' },
      { title: 'AI Asset Generator', href: '/game-development/asset-generator', icon: Sparkle, description: 'AI image generation', group: 'Production' },
      { title: 'Relationships', href: '/game-development/relationships', icon: Network, description: 'Entity graph', group: 'Production' },
      { title: 'Activity Feed', href: '/game-development/activity', icon: Activity, description: 'Recent activity', group: 'Production' },
      { title: 'Settings', href: '/game-development/settings', icon: Settings, description: 'Module settings' },
    ],
  },
};

export const getModuleRoute = (slug: string): ModuleRouteConfig | undefined => {
  return MODULE_ROUTES[slug];
};

export const getAllModuleRoutes = (): ModuleRouteConfig[] => {
  return Object.values(MODULE_ROUTES);
};

export const getModuleSections = (slug: string): ModuleSectionItem[] => {
  return MODULE_ROUTES[slug]?.sections || [];
};
