/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TowRouteImport } from './routes/tow'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffReferralRouteImport } from './routes/staff.referral'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as DashboardTowRouteImport } from './routes/dashboard.tow'
import { Route as DashboardSearchesRouteImport } from './routes/dashboard.searches'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardLikesRouteImport } from './routes/dashboard.likes'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminRedemptionsRouteImport } from './routes/admin.redemptions'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminCurrenciesRouteImport } from './routes/admin.currencies'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdvertisingRouteImport } from './routes/admin.advertising'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as RCodePosterRouteImport } from './routes/r.$code.poster'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ListingIdEditRouteImport } from './routes/listing.$id.edit'
import { Route as ApiPublicPaymentEventsRouteImport } from './routes/api/public/payment-events'
import { Route as AdminRedemptionsStaffIdRouteImport } from './routes/admin.redemptions.$staffId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicFxRefreshRouteImport } from './routes/api/public/fx/refresh'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TowRoute = TowRouteImport.update({
  id: '/tow',
  path: '/tow',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffReferralRoute = StaffReferralRouteImport.update({
  id: '/staff/referral',
  path: '/staff/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTowRoute = DashboardTowRouteImport.update({
  id: '/tow',
  path: '/tow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchesRoute = DashboardSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLikesRoute = DashboardLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedemptionsRoute = AdminRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisingRoute = AdminAdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const RCodePosterRoute = RCodePosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => RCodeRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdEditRoute = ListingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ListingIdRoute,
} as any)
const ApiPublicPaymentEventsRoute = ApiPublicPaymentEventsRouteImport.update({
  id: '/api/public/payment-events',
  path: '/api/public/payment-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedemptionsStaffIdRoute = AdminRedemptionsStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => AdminRedemptionsRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFxRefreshRoute = ApiPublicFxRefreshRouteImport.update({
  id: '/api/public/fx/refresh',
  path: '/api/public/fx/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/staff/referral': typeof StaffReferralRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/redemptions/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/staff/referral': typeof StaffReferralRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/redemptions/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/seller/$id': typeof SellerIdRoute
  '/staff/referral': typeof StaffReferralRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/redemptions/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/currencies'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/r/$code'
    | '/seller/$id'
    | '/staff/referral'
    | '/admin/'
    | '/dashboard/'
    | '/admin/redemptions/$staffId'
    | '/api/public/payment-events'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/r/$code/poster'
    | '/api/public/fx/refresh'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/contact'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/currencies'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/r/$code'
    | '/seller/$id'
    | '/staff/referral'
    | '/admin'
    | '/dashboard'
    | '/admin/redemptions/$staffId'
    | '/api/public/payment-events'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/r/$code/poster'
    | '/api/public/fx/refresh'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/currencies'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/searches'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/r/$code'
    | '/seller/$id'
    | '/staff/referral'
    | '/admin/'
    | '/dashboard/'
    | '/admin/redemptions/$staffId'
    | '/api/public/payment-events'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/r/$code/poster'
    | '/api/public/fx/refresh'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TowRoute: typeof TowRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ListingIdRoute: typeof ListingIdRouteWithChildren
  RCodeRoute: typeof RCodeRouteWithChildren
  SellerIdRoute: typeof SellerIdRoute
  StaffReferralRoute: typeof StaffReferralRoute
  ApiPublicPaymentEventsRoute: typeof ApiPublicPaymentEventsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicFxRefreshRoute: typeof ApiPublicFxRefreshRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tow': {
      id: '/tow'
      path: '/tow'
      fullPath: '/tow'
      preLoaderRoute: typeof TowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/referral': {
      id: '/staff/referral'
      path: '/staff/referral'
      fullPath: '/staff/referral'
      preLoaderRoute: typeof StaffReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tow': {
      id: '/dashboard/tow'
      path: '/tow'
      fullPath: '/dashboard/tow'
      preLoaderRoute: typeof DashboardTowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/searches': {
      id: '/dashboard/searches'
      path: '/searches'
      fullPath: '/dashboard/searches'
      preLoaderRoute: typeof DashboardSearchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/likes': {
      id: '/dashboard/likes'
      path: '/likes'
      fullPath: '/dashboard/likes'
      preLoaderRoute: typeof DashboardLikesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redemptions': {
      id: '/admin/redemptions'
      path: '/redemptions'
      fullPath: '/admin/redemptions'
      preLoaderRoute: typeof AdminRedemptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertising': {
      id: '/admin/advertising'
      path: '/advertising'
      fullPath: '/admin/advertising'
      preLoaderRoute: typeof AdminAdvertisingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$code/poster': {
      id: '/r/$code/poster'
      path: '/poster'
      fullPath: '/r/$code/poster'
      preLoaderRoute: typeof RCodePosterRouteImport
      parentRoute: typeof RCodeRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id/edit': {
      id: '/listing/$id/edit'
      path: '/edit'
      fullPath: '/listing/$id/edit'
      preLoaderRoute: typeof ListingIdEditRouteImport
      parentRoute: typeof ListingIdRoute
    }
    '/api/public/payment-events': {
      id: '/api/public/payment-events'
      path: '/api/public/payment-events'
      fullPath: '/api/public/payment-events'
      preLoaderRoute: typeof ApiPublicPaymentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redemptions/$staffId': {
      id: '/admin/redemptions/$staffId'
      path: '/$staffId'
      fullPath: '/admin/redemptions/$staffId'
      preLoaderRoute: typeof AdminRedemptionsStaffIdRouteImport
      parentRoute: typeof AdminRedemptionsRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fx/refresh': {
      id: '/api/public/fx/refresh'
      path: '/api/public/fx/refresh'
      fullPath: '/api/public/fx/refresh'
      preLoaderRoute: typeof ApiPublicFxRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRedemptionsRouteChildren {
  AdminRedemptionsStaffIdRoute: typeof AdminRedemptionsStaffIdRoute
}

const AdminRedemptionsRouteChildren: AdminRedemptionsRouteChildren = {
  AdminRedemptionsStaffIdRoute: AdminRedemptionsStaffIdRoute,
}

const AdminRedemptionsRouteWithChildren =
  AdminRedemptionsRoute._addFileChildren(AdminRedemptionsRouteChildren)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAdvertisingRoute: typeof AdminAdvertisingRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRedemptionsRoute: typeof AdminRedemptionsRouteWithChildren
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAdvertisingRoute: AdminAdvertisingRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRedemptionsRoute: AdminRedemptionsRouteWithChildren,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardLikesRoute: typeof DashboardLikesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSearchesRoute: typeof DashboardSearchesRoute
  DashboardTowRoute: typeof DashboardTowRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardLikesRoute: DashboardLikesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSearchesRoute: DashboardSearchesRoute,
  DashboardTowRoute: DashboardTowRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ListingIdRouteChildren {
  ListingIdEditRoute: typeof ListingIdEditRoute
}

const ListingIdRouteChildren: ListingIdRouteChildren = {
  ListingIdEditRoute: ListingIdEditRoute,
}

const ListingIdRouteWithChildren = ListingIdRoute._addFileChildren(
  ListingIdRouteChildren,
)

interface RCodeRouteChildren {
  RCodePosterRoute: typeof RCodePosterRoute
}

const RCodeRouteChildren: RCodeRouteChildren = {
  RCodePosterRoute: RCodePosterRoute,
}

const RCodeRouteWithChildren = RCodeRoute._addFileChildren(RCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TowRoute: TowRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ListingIdRoute: ListingIdRouteWithChildren,
  RCodeRoute: RCodeRouteWithChildren,
  SellerIdRoute: SellerIdRoute,
  StaffReferralRoute: StaffReferralRoute,
  ApiPublicPaymentEventsRoute: ApiPublicPaymentEventsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicFxRefreshRoute: ApiPublicFxRefreshRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
