/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TowRouteImport } from './routes/tow'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SellRouteImport } from './routes/sell'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as MyQrRouteImport } from './routes/my-qr'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as RidesIndexRouteImport } from './routes/rides.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as SellerIdRouteImport } from './routes/seller.$id'
import { Route as SellImportRouteImport } from './routes/sell.import'
import { Route as RidesSlugRouteImport } from './routes/rides.$slug'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as GoProductIdRouteImport } from './routes/go.$productId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardVerificationRouteImport } from './routes/dashboard.verification'
import { Route as DashboardTowRouteImport } from './routes/dashboard.tow'
import { Route as DashboardShopFavoritesRouteImport } from './routes/dashboard.shop-favorites'
import { Route as DashboardSearchesRouteImport } from './routes/dashboard.searches'
import { Route as DashboardRidesRouteImport } from './routes/dashboard.rides'
import { Route as DashboardReferralRouteImport } from './routes/dashboard.referral'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardLikesRouteImport } from './routes/dashboard.likes'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardBusinessesRouteImport } from './routes/dashboard.businesses'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BusinessesSubmitRouteImport } from './routes/businesses.submit'
import { Route as BusinessesSlugRouteImport } from './routes/businesses.$slug'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AdminVerificationsRouteImport } from './routes/admin.verifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTypeSuggestionsRouteImport } from './routes/admin.type-suggestions'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminSandboxRouteImport } from './routes/admin.sandbox'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminRedemptionsRouteImport } from './routes/admin.redemptions'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPerformanceRouteImport } from './routes/admin.performance'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminCurrenciesRouteImport } from './routes/admin.currencies'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdvertisingRouteImport } from './routes/admin.advertising'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as ShopPSlugRouteImport } from './routes/shop.p.$slug'
import { Route as RCodePosterRouteImport } from './routes/r.$code.poster'
import { Route as PaymentsIdReceiptRouteImport } from './routes/payments.$id.receipt'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ListingIdEditRouteImport } from './routes/listing.$id.edit'
import { Route as DashboardRidesNewRouteImport } from './routes/dashboard.rides_.new'
import { Route as ApiPublicPaymentEventsRouteImport } from './routes/api/public/payment-events'
import { Route as ApiPublicGeocodeRouteImport } from './routes/api/public/geocode'
import { Route as ApiAdminCreateUserRouteImport } from './routes/api/admin/create-user'
import { Route as AdminRedemptionsStaffIdRouteImport } from './routes/admin.redemptions_.$staffId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as DashboardRidesIdEditRouteImport } from './routes/dashboard.rides_.$id.edit'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicFxRefreshRouteImport } from './routes/api/public/fx/refresh'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TowRoute = TowRouteImport.update({
  id: '/tow',
  path: '/tow',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const MyQrRoute = MyQrRouteImport.update({
  id: '/my-qr',
  path: '/my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/shop/$category',
  path: '/shop/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIdRoute = SellerIdRouteImport.update({
  id: '/seller/$id',
  path: '/seller/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellImportRoute = SellImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SellRoute,
} as any)
const RidesSlugRoute = RidesSlugRouteImport.update({
  id: '/rides/$slug',
  path: '/rides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GoProductIdRoute = GoProductIdRouteImport.update({
  id: '/go/$productId',
  path: '/go/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVerificationRoute = DashboardVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTowRoute = DashboardTowRouteImport.update({
  id: '/tow',
  path: '/tow',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShopFavoritesRoute = DashboardShopFavoritesRouteImport.update({
  id: '/shop-favorites',
  path: '/shop-favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchesRoute = DashboardSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRidesRoute = DashboardRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralRoute = DashboardReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLikesRoute = DashboardLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessesRoute = DashboardBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSubmitRoute = BusinessesSubmitRouteImport.update({
  id: '/businesses/submit',
  path: '/businesses/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesSlugRoute = BusinessesSlugRouteImport.update({
  id: '/businesses/$slug',
  path: '/businesses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTypeSuggestionsRoute = AdminTypeSuggestionsRouteImport.update({
  id: '/type-suggestions',
  path: '/type-suggestions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSandboxRoute = AdminSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedemptionsRoute = AdminRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurrenciesRoute = AdminCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisingRoute = AdminAdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const ShopPSlugRoute = ShopPSlugRouteImport.update({
  id: '/shop/p/$slug',
  path: '/shop/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodePosterRoute = RCodePosterRouteImport.update({
  id: '/poster',
  path: '/poster',
  getParentRoute: () => RCodeRoute,
} as any)
const PaymentsIdReceiptRoute = PaymentsIdReceiptRouteImport.update({
  id: '/$id/receipt',
  path: '/$id/receipt',
  getParentRoute: () => PaymentsRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdEditRoute = ListingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ListingIdRoute,
} as any)
const DashboardRidesNewRoute = DashboardRidesNewRouteImport.update({
  id: '/rides_/new',
  path: '/rides/new',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicPaymentEventsRoute = ApiPublicPaymentEventsRouteImport.update({
  id: '/api/public/payment-events',
  path: '/api/public/payment-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeocodeRoute = ApiPublicGeocodeRouteImport.update({
  id: '/api/public/geocode',
  path: '/api/public/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreateUserRoute = ApiAdminCreateUserRouteImport.update({
  id: '/api/admin/create-user',
  path: '/api/admin/create-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedemptionsStaffIdRoute = AdminRedemptionsStaffIdRouteImport.update({
  id: '/redemptions_/$staffId',
  path: '/redemptions/$staffId',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRidesIdEditRoute = DashboardRidesIdEditRouteImport.update({
  id: '/rides_/$id/edit',
  path: '/rides/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFxRefreshRoute = ApiPublicFxRefreshRouteImport.update({
  id: '/api/public/fx/refresh',
  path: '/api/public/fx/refresh',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-qr': typeof MyQrRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sandbox': typeof AdminSandboxRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/type-suggestions': typeof AdminTypeSuggestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/submit': typeof BusinessesSubmitRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referral': typeof DashboardReferralRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/shop-favorites': typeof DashboardShopFavoritesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$productId': typeof GoProductIdRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/rides/$slug': typeof RidesSlugRoute
  '/sell/import': typeof SellImportRoute
  '/seller/$id': typeof SellerIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/redemptions/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/admin/create-user': typeof ApiAdminCreateUserRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/dashboard/rides/new': typeof DashboardRidesNewRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/payments/$id/receipt': typeof PaymentsIdReceiptRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/rides/$id/edit': typeof DashboardRidesIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-qr': typeof MyQrRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sandbox': typeof AdminSandboxRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/type-suggestions': typeof AdminTypeSuggestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/submit': typeof BusinessesSubmitRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referral': typeof DashboardReferralRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/shop-favorites': typeof DashboardShopFavoritesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$productId': typeof GoProductIdRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/rides/$slug': typeof RidesSlugRoute
  '/sell/import': typeof SellImportRoute
  '/seller/$id': typeof SellerIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin': typeof AdminIndexRoute
  '/businesses': typeof BusinessesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/rides': typeof RidesIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/redemptions/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/admin/create-user': typeof ApiAdminCreateUserRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/dashboard/rides/new': typeof DashboardRidesNewRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/payments/$id/receipt': typeof PaymentsIdReceiptRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/rides/$id/edit': typeof DashboardRidesIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/export': typeof ExportRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/my-qr': typeof MyQrRoute
  '/payments': typeof PaymentsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRouteWithChildren
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tow': typeof TowRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/advertising': typeof AdminAdvertisingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/currencies': typeof AdminCurrenciesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/listings': typeof AdminListingsRoute
  '/admin/performance': typeof AdminPerformanceRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/sandbox': typeof AdminSandboxRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/type-suggestions': typeof AdminTypeSuggestionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/businesses/$slug': typeof BusinessesSlugRoute
  '/businesses/submit': typeof BusinessesSubmitRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/businesses': typeof DashboardBusinessesRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/likes': typeof DashboardLikesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referral': typeof DashboardReferralRoute
  '/dashboard/rides': typeof DashboardRidesRoute
  '/dashboard/searches': typeof DashboardSearchesRoute
  '/dashboard/shop-favorites': typeof DashboardShopFavoritesRoute
  '/dashboard/tow': typeof DashboardTowRoute
  '/dashboard/verification': typeof DashboardVerificationRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/go/$productId': typeof GoProductIdRoute
  '/listing/$id': typeof ListingIdRouteWithChildren
  '/r/$code': typeof RCodeRouteWithChildren
  '/rides/$slug': typeof RidesSlugRoute
  '/sell/import': typeof SellImportRoute
  '/seller/$id': typeof SellerIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/admin/': typeof AdminIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/redemptions_/$staffId': typeof AdminRedemptionsStaffIdRoute
  '/api/admin/create-user': typeof ApiAdminCreateUserRoute
  '/api/public/geocode': typeof ApiPublicGeocodeRoute
  '/api/public/payment-events': typeof ApiPublicPaymentEventsRoute
  '/dashboard/rides_/new': typeof DashboardRidesNewRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/payments/$id/receipt': typeof PaymentsIdReceiptRoute
  '/r/$code/poster': typeof RCodePosterRoute
  '/shop/p/$slug': typeof ShopPSlugRoute
  '/api/public/fx/refresh': typeof ApiPublicFxRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/dashboard/rides_/$id/edit': typeof DashboardRidesIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/contact'
    | '/dashboard'
    | '/export'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/map'
    | '/my-qr'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/businesses'
    | '/admin/currencies'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sandbox'
    | '/admin/shop'
    | '/admin/type-suggestions'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/businesses/$slug'
    | '/businesses/submit'
    | '/checkout/return'
    | '/dashboard/billing'
    | '/dashboard/businesses'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/referral'
    | '/dashboard/rides'
    | '/dashboard/searches'
    | '/dashboard/shop-favorites'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/go/$productId'
    | '/listing/$id'
    | '/r/$code'
    | '/rides/$slug'
    | '/sell/import'
    | '/seller/$id'
    | '/shop/$category'
    | '/admin/'
    | '/businesses/'
    | '/dashboard/'
    | '/rides/'
    | '/shop/'
    | '/admin/redemptions/$staffId'
    | '/api/admin/create-user'
    | '/api/public/geocode'
    | '/api/public/payment-events'
    | '/dashboard/rides/new'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/payments/$id/receipt'
    | '/r/$code/poster'
    | '/shop/p/$slug'
    | '/api/public/fx/refresh'
    | '/api/public/payments/webhook'
    | '/dashboard/rides/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/contact'
    | '/export'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/map'
    | '/my-qr'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/businesses'
    | '/admin/currencies'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sandbox'
    | '/admin/shop'
    | '/admin/type-suggestions'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/businesses/$slug'
    | '/businesses/submit'
    | '/checkout/return'
    | '/dashboard/billing'
    | '/dashboard/businesses'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/referral'
    | '/dashboard/rides'
    | '/dashboard/searches'
    | '/dashboard/shop-favorites'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/go/$productId'
    | '/listing/$id'
    | '/r/$code'
    | '/rides/$slug'
    | '/sell/import'
    | '/seller/$id'
    | '/shop/$category'
    | '/admin'
    | '/businesses'
    | '/dashboard'
    | '/rides'
    | '/shop'
    | '/admin/redemptions/$staffId'
    | '/api/admin/create-user'
    | '/api/public/geocode'
    | '/api/public/payment-events'
    | '/dashboard/rides/new'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/payments/$id/receipt'
    | '/r/$code/poster'
    | '/shop/p/$slug'
    | '/api/public/fx/refresh'
    | '/api/public/payments/webhook'
    | '/dashboard/rides/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/contact'
    | '/dashboard'
    | '/export'
    | '/forgot-password'
    | '/guidelines'
    | '/login'
    | '/map'
    | '/my-qr'
    | '/payments'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/tow'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin/accounts'
    | '/admin/advertising'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/businesses'
    | '/admin/currencies'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/performance'
    | '/admin/pricing'
    | '/admin/redemptions'
    | '/admin/referrals'
    | '/admin/reports'
    | '/admin/sandbox'
    | '/admin/shop'
    | '/admin/type-suggestions'
    | '/admin/users'
    | '/admin/verifications'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/browse/$category'
    | '/businesses/$slug'
    | '/businesses/submit'
    | '/checkout/return'
    | '/dashboard/billing'
    | '/dashboard/businesses'
    | '/dashboard/favorites'
    | '/dashboard/likes'
    | '/dashboard/messages'
    | '/dashboard/profile'
    | '/dashboard/referral'
    | '/dashboard/rides'
    | '/dashboard/searches'
    | '/dashboard/shop-favorites'
    | '/dashboard/tow'
    | '/dashboard/verification'
    | '/email/unsubscribe'
    | '/go/$productId'
    | '/listing/$id'
    | '/r/$code'
    | '/rides/$slug'
    | '/sell/import'
    | '/seller/$id'
    | '/shop/$category'
    | '/admin/'
    | '/businesses/'
    | '/dashboard/'
    | '/rides/'
    | '/shop/'
    | '/admin/redemptions_/$staffId'
    | '/api/admin/create-user'
    | '/api/public/geocode'
    | '/api/public/payment-events'
    | '/dashboard/rides_/new'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/payments/$id/receipt'
    | '/r/$code/poster'
    | '/shop/p/$slug'
    | '/api/public/fx/refresh'
    | '/api/public/payments/webhook'
    | '/dashboard/rides_/$id/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExportRoute: typeof ExportRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MyQrRoute: typeof MyQrRoute
  PaymentsRoute: typeof PaymentsRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRouteWithChildren
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TowRoute: typeof TowRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  BusinessesSlugRoute: typeof BusinessesSlugRoute
  BusinessesSubmitRoute: typeof BusinessesSubmitRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GoProductIdRoute: typeof GoProductIdRoute
  ListingIdRoute: typeof ListingIdRouteWithChildren
  RCodeRoute: typeof RCodeRouteWithChildren
  RidesSlugRoute: typeof RidesSlugRoute
  SellerIdRoute: typeof SellerIdRoute
  ShopCategoryRoute: typeof ShopCategoryRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiAdminCreateUserRoute: typeof ApiAdminCreateUserRoute
  ApiPublicGeocodeRoute: typeof ApiPublicGeocodeRoute
  ApiPublicPaymentEventsRoute: typeof ApiPublicPaymentEventsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ShopPSlugRoute: typeof ShopPSlugRoute
  ApiPublicFxRefreshRoute: typeof ApiPublicFxRefreshRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tow': {
      id: '/tow'
      path: '/tow'
      fullPath: '/tow'
      preLoaderRoute: typeof TowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-qr': {
      id: '/my-qr'
      path: '/my-qr'
      fullPath: '/my-qr'
      preLoaderRoute: typeof MyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$id': {
      id: '/seller/$id'
      path: '/seller/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof SellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/import': {
      id: '/sell/import'
      path: '/import'
      fullPath: '/sell/import'
      preLoaderRoute: typeof SellImportRouteImport
      parentRoute: typeof SellRoute
    }
    '/rides/$slug': {
      id: '/rides/$slug'
      path: '/rides/$slug'
      fullPath: '/rides/$slug'
      preLoaderRoute: typeof RidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$productId': {
      id: '/go/$productId'
      path: '/go/$productId'
      fullPath: '/go/$productId'
      preLoaderRoute: typeof GoProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/verification': {
      id: '/dashboard/verification'
      path: '/verification'
      fullPath: '/dashboard/verification'
      preLoaderRoute: typeof DashboardVerificationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tow': {
      id: '/dashboard/tow'
      path: '/tow'
      fullPath: '/dashboard/tow'
      preLoaderRoute: typeof DashboardTowRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shop-favorites': {
      id: '/dashboard/shop-favorites'
      path: '/shop-favorites'
      fullPath: '/dashboard/shop-favorites'
      preLoaderRoute: typeof DashboardShopFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/searches': {
      id: '/dashboard/searches'
      path: '/searches'
      fullPath: '/dashboard/searches'
      preLoaderRoute: typeof DashboardSearchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rides': {
      id: '/dashboard/rides'
      path: '/rides'
      fullPath: '/dashboard/rides'
      preLoaderRoute: typeof DashboardRidesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referral': {
      id: '/dashboard/referral'
      path: '/referral'
      fullPath: '/dashboard/referral'
      preLoaderRoute: typeof DashboardReferralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/likes': {
      id: '/dashboard/likes'
      path: '/likes'
      fullPath: '/dashboard/likes'
      preLoaderRoute: typeof DashboardLikesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/businesses': {
      id: '/dashboard/businesses'
      path: '/businesses'
      fullPath: '/dashboard/businesses'
      preLoaderRoute: typeof DashboardBusinessesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/submit': {
      id: '/businesses/submit'
      path: '/businesses/submit'
      fullPath: '/businesses/submit'
      preLoaderRoute: typeof BusinessesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$slug': {
      id: '/businesses/$slug'
      path: '/businesses/$slug'
      fullPath: '/businesses/$slug'
      preLoaderRoute: typeof BusinessesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/type-suggestions': {
      id: '/admin/type-suggestions'
      path: '/type-suggestions'
      fullPath: '/admin/type-suggestions'
      preLoaderRoute: typeof AdminTypeSuggestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sandbox': {
      id: '/admin/sandbox'
      path: '/sandbox'
      fullPath: '/admin/sandbox'
      preLoaderRoute: typeof AdminSandboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redemptions': {
      id: '/admin/redemptions'
      path: '/redemptions'
      fullPath: '/admin/redemptions'
      preLoaderRoute: typeof AdminRedemptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/performance': {
      id: '/admin/performance'
      path: '/performance'
      fullPath: '/admin/performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/currencies': {
      id: '/admin/currencies'
      path: '/currencies'
      fullPath: '/admin/currencies'
      preLoaderRoute: typeof AdminCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertising': {
      id: '/admin/advertising'
      path: '/advertising'
      fullPath: '/admin/advertising'
      preLoaderRoute: typeof AdminAdvertisingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/p/$slug': {
      id: '/shop/p/$slug'
      path: '/shop/p/$slug'
      fullPath: '/shop/p/$slug'
      preLoaderRoute: typeof ShopPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code/poster': {
      id: '/r/$code/poster'
      path: '/poster'
      fullPath: '/r/$code/poster'
      preLoaderRoute: typeof RCodePosterRouteImport
      parentRoute: typeof RCodeRoute
    }
    '/payments/$id/receipt': {
      id: '/payments/$id/receipt'
      path: '/$id/receipt'
      fullPath: '/payments/$id/receipt'
      preLoaderRoute: typeof PaymentsIdReceiptRouteImport
      parentRoute: typeof PaymentsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id/edit': {
      id: '/listing/$id/edit'
      path: '/edit'
      fullPath: '/listing/$id/edit'
      preLoaderRoute: typeof ListingIdEditRouteImport
      parentRoute: typeof ListingIdRoute
    }
    '/dashboard/rides_/new': {
      id: '/dashboard/rides_/new'
      path: '/rides/new'
      fullPath: '/dashboard/rides/new'
      preLoaderRoute: typeof DashboardRidesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/payment-events': {
      id: '/api/public/payment-events'
      path: '/api/public/payment-events'
      fullPath: '/api/public/payment-events'
      preLoaderRoute: typeof ApiPublicPaymentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geocode': {
      id: '/api/public/geocode'
      path: '/api/public/geocode'
      fullPath: '/api/public/geocode'
      preLoaderRoute: typeof ApiPublicGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-user': {
      id: '/api/admin/create-user'
      path: '/api/admin/create-user'
      fullPath: '/api/admin/create-user'
      preLoaderRoute: typeof ApiAdminCreateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redemptions_/$staffId': {
      id: '/admin/redemptions_/$staffId'
      path: '/redemptions/$staffId'
      fullPath: '/admin/redemptions/$staffId'
      preLoaderRoute: typeof AdminRedemptionsStaffIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rides_/$id/edit': {
      id: '/dashboard/rides_/$id/edit'
      path: '/rides/$id/edit'
      fullPath: '/dashboard/rides/$id/edit'
      preLoaderRoute: typeof DashboardRidesIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fx/refresh': {
      id: '/api/public/fx/refresh'
      path: '/api/public/fx/refresh'
      fullPath: '/api/public/fx/refresh'
      preLoaderRoute: typeof ApiPublicFxRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminAdvertisingRoute: typeof AdminAdvertisingRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCurrenciesRoute: typeof AdminCurrenciesRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminListingsRoute: typeof AdminListingsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRedemptionsRoute: typeof AdminRedemptionsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSandboxRoute: typeof AdminSandboxRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminTypeSuggestionsRoute: typeof AdminTypeSuggestionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRedemptionsStaffIdRoute: typeof AdminRedemptionsStaffIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminAdvertisingRoute: AdminAdvertisingRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCurrenciesRoute: AdminCurrenciesRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminListingsRoute: AdminListingsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRedemptionsRoute: AdminRedemptionsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSandboxRoute: AdminSandboxRoute,
  AdminShopRoute: AdminShopRoute,
  AdminTypeSuggestionsRoute: AdminTypeSuggestionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRedemptionsStaffIdRoute: AdminRedemptionsStaffIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBusinessesRoute: typeof DashboardBusinessesRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardLikesRoute: typeof DashboardLikesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralRoute: typeof DashboardReferralRoute
  DashboardRidesRoute: typeof DashboardRidesRoute
  DashboardSearchesRoute: typeof DashboardSearchesRoute
  DashboardShopFavoritesRoute: typeof DashboardShopFavoritesRoute
  DashboardTowRoute: typeof DashboardTowRoute
  DashboardVerificationRoute: typeof DashboardVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRidesNewRoute: typeof DashboardRidesNewRoute
  DashboardRidesIdEditRoute: typeof DashboardRidesIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBusinessesRoute: DashboardBusinessesRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardLikesRoute: DashboardLikesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralRoute: DashboardReferralRoute,
  DashboardRidesRoute: DashboardRidesRoute,
  DashboardSearchesRoute: DashboardSearchesRoute,
  DashboardShopFavoritesRoute: DashboardShopFavoritesRoute,
  DashboardTowRoute: DashboardTowRoute,
  DashboardVerificationRoute: DashboardVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRidesNewRoute: DashboardRidesNewRoute,
  DashboardRidesIdEditRoute: DashboardRidesIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PaymentsRouteChildren {
  PaymentsIdReceiptRoute: typeof PaymentsIdReceiptRoute
}

const PaymentsRouteChildren: PaymentsRouteChildren = {
  PaymentsIdReceiptRoute: PaymentsIdReceiptRoute,
}

const PaymentsRouteWithChildren = PaymentsRoute._addFileChildren(
  PaymentsRouteChildren,
)

interface SellRouteChildren {
  SellImportRoute: typeof SellImportRoute
}

const SellRouteChildren: SellRouteChildren = {
  SellImportRoute: SellImportRoute,
}

const SellRouteWithChildren = SellRoute._addFileChildren(SellRouteChildren)

interface ListingIdRouteChildren {
  ListingIdEditRoute: typeof ListingIdEditRoute
}

const ListingIdRouteChildren: ListingIdRouteChildren = {
  ListingIdEditRoute: ListingIdEditRoute,
}

const ListingIdRouteWithChildren = ListingIdRoute._addFileChildren(
  ListingIdRouteChildren,
)

interface RCodeRouteChildren {
  RCodePosterRoute: typeof RCodePosterRoute
}

const RCodeRouteChildren: RCodeRouteChildren = {
  RCodePosterRoute: RCodePosterRoute,
}

const RCodeRouteWithChildren = RCodeRoute._addFileChildren(RCodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExportRoute: ExportRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MyQrRoute: MyQrRoute,
  PaymentsRoute: PaymentsRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRouteWithChildren,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TowRoute: TowRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  BusinessesSlugRoute: BusinessesSlugRoute,
  BusinessesSubmitRoute: BusinessesSubmitRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GoProductIdRoute: GoProductIdRoute,
  ListingIdRoute: ListingIdRouteWithChildren,
  RCodeRoute: RCodeRouteWithChildren,
  RidesSlugRoute: RidesSlugRoute,
  SellerIdRoute: SellerIdRoute,
  ShopCategoryRoute: ShopCategoryRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiAdminCreateUserRoute: ApiAdminCreateUserRoute,
  ApiPublicGeocodeRoute: ApiPublicGeocodeRoute,
  ApiPublicPaymentEventsRoute: ApiPublicPaymentEventsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ShopPSlugRoute: ShopPSlugRoute,
  ApiPublicFxRefreshRoute: ApiPublicFxRefreshRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
