
-- Seed service catalog entries for business types that previously had none,
-- and round out a few existing types.
INSERT INTO public.service_catalog (business_type_slug, key, title, description, default_unit, sort_order, active) VALUES
-- Accessories / customization
('accessories','acc_dashcam_install','Dashcam Installation','Front or front+rear dashcam install with hardwire.','service',10,true),
('accessories','acc_alarm_install','Car Alarm / Immobilizer Install',NULL,'service',20,true),
('accessories','acc_led_upgrade','LED Headlight / Foglight Upgrade',NULL,'service',30,true),
('accessories','acc_remote_start','Remote Start Install',NULL,'service',40,true),
('accessories','acc_roof_rack','Roof Rack / Cargo Carrier Install',NULL,'service',50,true),
('accessories','acc_seat_cover','Custom Seat Cover Fitting',NULL,'set',60,true),
('accessories','acc_floor_mats','Custom Floor Mats',NULL,'set',70,true),
-- Audio & tint
('audio_tint','at_window_tint','Window Tinting (full vehicle)',NULL,'vehicle',10,true),
('audio_tint','at_windshield_tint','Windshield Tinting',NULL,'service',20,true),
('audio_tint','at_speaker_install','Speaker Replacement',NULL,'set',30,true),
('audio_tint','at_head_unit_install','Head Unit / Stereo Install',NULL,'service',40,true),
('audio_tint','at_amp_sub_install','Amp & Subwoofer Install',NULL,'service',50,true),
('audio_tint','at_sound_deadening','Sound Deadening',NULL,'vehicle',60,true),
-- Body & paint
('body_paint','bp_full_repaint','Full Vehicle Repaint',NULL,'vehicle',10,true),
('body_paint','bp_panel_repaint','Single Panel Repaint',NULL,'service',20,true),
('body_paint','bp_dent_repair','Dent Repair (PDR)',NULL,'service',30,true),
('body_paint','bp_bumper_repair','Bumper Repair',NULL,'service',40,true),
('body_paint','bp_scratch_buff','Scratch Removal / Buffing',NULL,'service',50,true),
('body_paint','bp_collision_estimate','Collision Repair Estimate',NULL,'service',60,true),
('body_paint','bp_insurance_claim','Insurance Claim Assistance',NULL,'service',70,true),
-- Corporate / fleet
('corporate','cf_fleet_lease','Fleet Lease (long-term)',NULL,'vehicle',10,true),
('corporate','cf_fleet_maintenance','Fleet Maintenance Contract',NULL,'vehicle',20,true),
('corporate','cf_driver_supply','Driver Supply',NULL,'day',30,true),
('corporate','cf_chauffeur','Chauffeur Service',NULL,'hr',40,true),
-- Dealerships (new cars)
('dealership','dl_new_car_sale','New Vehicle Sale',NULL,'vehicle',10,true),
('dealership','dl_test_drive','Test Drive Booking',NULL,'service',20,true),
('dealership','dl_trade_in','Trade-in Appraisal',NULL,'service',30,true),
('dealership','dl_financing','In-house Financing',NULL,'service',40,true),
('dealership','dl_warranty','Warranty Registration',NULL,'service',50,true),
('dealership','dl_pms','Preventive Maintenance Service (PMS)',NULL,'service',60,true),
-- Used car dealer
('used_dealership','ud_used_sale','Used Vehicle Sale',NULL,'vehicle',10,true),
('used_dealership','ud_buy_your_car','We Buy Your Car',NULL,'vehicle',20,true),
('used_dealership','ud_trade_in','Trade-in Appraisal',NULL,'service',30,true),
('used_dealership','ud_consign','Consignment',NULL,'service',40,true),
('used_dealership','ud_financing_assist','Financing Assistance',NULL,'service',50,true),
('used_dealership','ud_recon','Reconditioning / Detailing',NULL,'vehicle',60,true),
-- Driving school
('driving_school','ds_basic_course','Basic Driving Course (manual)',NULL,'session',10,true),
('driving_school','ds_basic_at','Basic Driving Course (automatic)',NULL,'session',20,true),
('driving_school','ds_refresher','Refresher Course',NULL,'session',30,true),
('driving_school','ds_tdc','Theoretical Driving Course (TDC)',NULL,'session',40,true),
('driving_school','ds_pdc','Practical Driving Course (PDC)',NULL,'session',50,true),
('driving_school','ds_motor_course','Motorcycle Riding Course',NULL,'session',60,true),
-- Financing / loans
('financing','fn_auto_loan','Auto Loan Application',NULL,'service',10,true),
('financing','fn_motor_loan','Motorcycle Loan',NULL,'service',20,true),
('financing','fn_refinance','Auto Refinancing',NULL,'service',30,true),
('financing','fn_truck_loan','Commercial / Truck Loan',NULL,'service',40,true),
('financing','fn_loan_calc','Loan Pre-qualification',NULL,'service',50,true),
-- Inspection / emissions
('inspection','ip_pms_inspection','PMS / Multi-point Inspection',NULL,'vehicle',10,true),
('inspection','ip_pre_purchase','Pre-purchase Inspection',NULL,'vehicle',20,true),
('inspection','ip_emission_test','Emission Testing',NULL,'vehicle',30,true),
('inspection','ip_pmvic','PMVIC Roadworthiness Inspection',NULL,'vehicle',40,true),
('inspection','ip_obd_scan','OBD-II Diagnostic Scan',NULL,'service',50,true),
-- Insurance
('insurance','ins_ctpl','CTPL (mandatory liability)',NULL,'service',10,true),
('insurance','ins_comprehensive','Comprehensive Insurance',NULL,'service',20,true),
('insurance','ins_acts_of_nature','Acts of Nature Coverage',NULL,'service',30,true),
('insurance','ins_renewal','Policy Renewal',NULL,'service',40,true),
('insurance','ins_claim_assist','Claims Assistance',NULL,'service',50,true),
('insurance','ins_quote','Insurance Quotation',NULL,'service',60,true),
-- LTO services
('lto_services','lto_registration','LTO Vehicle Registration',NULL,'vehicle',10,true),
('lto_services','lto_renewal','LTO Registration Renewal',NULL,'vehicle',20,true),
('lto_services','lto_transfer','Transfer of Ownership',NULL,'service',30,true),
('lto_services','lto_change_color','Change of Color / Body',NULL,'service',40,true),
('lto_services','lto_plates','Plates / Sticker Release',NULL,'service',50,true),
('lto_services','lto_drivers_license','Driver''s License Application / Renewal',NULL,'service',60,true),
-- Motorcycle shop
('motorcycle_shop','mc_oil_change','Motorcycle Oil Change',NULL,'service',10,true),
('motorcycle_shop','mc_tire_change','Motorcycle Tire Change',NULL,'service',20,true),
('motorcycle_shop','mc_brake_service','Brake Service',NULL,'service',30,true),
('motorcycle_shop','mc_chain_sprocket','Chain & Sprocket Replacement','set','set',40,true),
('motorcycle_shop','mc_tune_up','Tune-up',NULL,'service',50,true),
('motorcycle_shop','mc_battery','Battery Replacement',NULL,'service',60,true),
('motorcycle_shop','mc_carb_clean','Carburetor Cleaning',NULL,'service',70,true),
('motorcycle_shop','mc_clutch','Clutch Service',NULL,'service',80,true),
-- Parts supplier / shop
('parts_accessories','pa_oem_parts','OEM Parts',NULL,'item',10,true),
('parts_accessories','pa_aftermarket','Aftermarket Parts',NULL,'item',20,true),
('parts_accessories','pa_brake_pads','Brake Pads',NULL,'set',30,true),
('parts_accessories','pa_filters','Filters (oil / air / fuel)',NULL,'item',40,true),
('parts_accessories','pa_battery','Battery',NULL,'item',50,true),
('parts_accessories','pa_belts_hoses','Belts & Hoses',NULL,'item',60,true),
('parts_accessories','pa_lubricants','Engine Oil / Lubricants',NULL,'L',70,true),
('parts_accessories','pa_tires','Tires',NULL,'item',80,true),
('parts_accessories','pa_special_order','Special Order / Sourcing',NULL,'service',90,true),
-- Vehicle rental
('rental','rt_self_drive','Self-drive Rental',NULL,'day',10,true),
('rental','rt_with_driver','Rental With Driver',NULL,'day',20,true),
('rental','rt_airport_transfer','Airport Transfer',NULL,'trip',30,true),
('rental','rt_hourly','Hourly Rental',NULL,'hr',40,true),
('rental','rt_long_term','Long-term Rental (monthly)',NULL,'month',50,true),
('rental','rt_van_rental','Van Rental',NULL,'day',60,true),
('rental','rt_truck_rental','Truck / Pickup Rental',NULL,'day',70,true),
-- Salvage / pick-a-part
('salvage','sv_used_part','Used Part (per item)',NULL,'item',10,true),
('salvage','sv_engine_assembly','Used Engine Assembly',NULL,'item',20,true),
('salvage','sv_transmission','Used Transmission',NULL,'item',30,true),
('salvage','sv_body_panel','Used Body Panel',NULL,'item',40,true),
('salvage','sv_buy_junk','We Buy Junk / Wrecked Cars',NULL,'vehicle',50,true),
('salvage','sv_dismantling','Vehicle Dismantling',NULL,'vehicle',60,true),
-- Transport / logistics
('transport','tl_lipat_bahay','Lipat-bahay (house move)',NULL,'trip',10,true),
('transport','tl_furniture_delivery','Furniture / Appliance Delivery',NULL,'trip',20,true),
('transport','tl_cargo_van','Cargo Van Hire',NULL,'trip',30,true),
('transport','tl_truck_hire','Truck Hire (6-wheeler+)',NULL,'trip',40,true),
('transport','tl_courier','Courier / Parcel Delivery',NULL,'delivery',50,true),
('transport','tl_intercity','Inter-city Freight',NULL,'trip',60,true),
('transport','tl_warehouse','Warehousing',NULL,'month',70,true),
-- "Other" — generic fallback
('other','oth_consultation','Consultation',NULL,'hr',10,true),
('other','oth_service_call','Service Call',NULL,'visit',20,true),
('other','oth_estimate','Estimate / Quotation',NULL,'service',30,true),
-- Round out existing types
('repair_shop','rs_battery_replace','Battery Replacement',NULL,'service',90,true),
('repair_shop','rs_clutch_service','Clutch Service',NULL,'service',100,true),
('repair_shop','rs_suspension','Suspension Repair',NULL,'service',110,true),
('repair_shop','rs_radiator_flush','Radiator Flush',NULL,'service',120,true),
('repair_shop','rs_transmission_service','Transmission Service',NULL,'service',130,true),
('repair_shop','rs_electrical','Electrical Diagnosis & Repair',NULL,'hr',140,true),
('tire_shop','ts_new_tire','New Tire (per tire)',NULL,'item',60,true),
('tire_shop','ts_used_tire','Used Tire (per tire)',NULL,'item',70,true),
('tire_shop','ts_tire_repair_patch','Tire Repair (patch / plug)',NULL,'service',80,true),
('tire_shop','ts_road_hazard','Road Hazard Warranty',NULL,'item',90,true),
('battery_shop','bs_new_battery','New Battery (with old trade-in)',NULL,'item',50,true),
('battery_shop','bs_alternator_test','Alternator / Charging System Test',NULL,'service',60,true),
('battery_shop','bs_battery_recharge','Battery Recharging',NULL,'service',70,true),
('carwash','cw_interior_detail','Interior Detail / Shampoo',NULL,'service',70,true),
('carwash','cw_paint_correction','Paint Correction',NULL,'service',80,true),
('carwash','cw_headlight_restore','Headlight Restoration',NULL,'service',90,true),
('fuel_station','fs_kerosene','Kerosene',NULL,'L',90,true),
('fuel_station','fs_lubricants','Engine Oil / Lubricants',NULL,'L',100,true),
('fuel_station','fs_air_water','Air & Water','Free or paid','service',110,true),
('fuel_station','fs_atm','ATM',NULL,'service',120,true),
('fuel_station','fs_convenience','Convenience Store',NULL,'service',130,true)
ON CONFLICT (business_type_slug, key) DO NOTHING;
