
-- 1. Add missing business types
INSERT INTO public.business_types (slug, label, sort_order) VALUES
  ('body_paint','Body & paint shop',25),
  ('carwash','Car wash & detailing',35),
  ('salvage','Salvage / pick-a-part',45)
ON CONFLICT (slug) DO NOTHING;

-- 2. Add columns
ALTER TABLE public.business_tags
  ADD COLUMN IF NOT EXISTS category text,
  ADD COLUMN IF NOT EXISTS is_popular boolean NOT NULL DEFAULT false;

-- 3. Ensure PK on slug
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'business_tags_pkey') THEN
    BEGIN
      ALTER TABLE public.business_tags ADD PRIMARY KEY (slug);
    EXCEPTION WHEN others THEN NULL;
    END;
  END IF;
END $$;

-- 4. Reseed
INSERT INTO public.business_tags (slug, label, type_slug, category, sort_order, is_popular) VALUES
-- REPAIR SHOP
('oil-change','Oil change','repair_shop','maintenance',1,true),
('tune-up','Tune-up','repair_shop','maintenance',2,true),
('brake-service','Brake service','repair_shop','brakes',3,true),
('brake-rotor','Brake rotor resurfacing','repair_shop','brakes',4,false),
('clutch-replacement','Clutch replacement','repair_shop','drivetrain',5,false),
('timing-belt','Timing belt','repair_shop','engine',6,false),
('timing-chain','Timing chain','repair_shop','engine',7,false),
('water-pump','Water pump','repair_shop','engine',8,false),
('radiator-service','Radiator service','repair_shop','cooling',9,false),
('coolant-flush','Coolant flush','repair_shop','cooling',10,false),
('transmission-flush','Transmission flush','repair_shop','drivetrain',11,false),
('cvt-service','CVT service','repair_shop','drivetrain',12,false),
('at-mt-repair','AT/MT repair','repair_shop','drivetrain',13,false),
('differential-service','Differential service','repair_shop','drivetrain',14,false),
('suspension-service','Suspension service','repair_shop','suspension',15,false),
('shock-strut','Shock & strut','repair_shop','suspension',16,false),
('ball-joints','Ball joints','repair_shop','suspension',17,false),
('tie-rods','Tie rods','repair_shop','suspension',18,false),
('wheel-bearings','Wheel bearings','repair_shop','suspension',19,false),
('alignment','Wheel alignment','repair_shop','wheels',20,true),
('tire-mount-balance','Tire mount & balance','repair_shop','wheels',21,true),
('tpms','TPMS service','repair_shop','wheels',22,false),
('aircon','Aircon service','repair_shop','climate',23,true),
('ac-recharge','AC recharge','repair_shop','climate',24,false),
('ac-compressor','AC compressor','repair_shop','climate',25,false),
('heater-core','Heater core','repair_shop','climate',26,false),
('electrical','Auto electrical','repair_shop','electrical',27,true),
('electrical-diagnostics','Electrical diagnostics','repair_shop','electrical',28,false),
('alternator','Alternator','repair_shop','electrical',29,false),
('starter','Starter','repair_shop','electrical',30,false),
('battery-service','Battery service','repair_shop','electrical',31,true),
('ecu-reflash','ECU scan / reflash','repair_shop','diagnostics',32,false),
('obd-diagnostics','OBD diagnostics','repair_shop','diagnostics',33,false),
('cel-diagnosis','Check-engine light','repair_shop','diagnostics',34,false),
('fuel-system-clean','Fuel system clean','repair_shop','fuel',35,false),
('fuel-pump','Fuel pump','repair_shop','fuel',36,false),
('injectors','Injectors','repair_shop','fuel',37,false),
('egr-clean','EGR clean','repair_shop','fuel',38,false),
('dpf-clean','DPF clean','repair_shop','fuel',39,false),
('turbo-service','Turbo service','repair_shop','engine',40,false),
('engine-overhaul','Engine overhaul','repair_shop','engine',41,false),
('head-gasket','Head gasket','repair_shop','engine',42,false),
('valve-adjustment','Valve adjustment','repair_shop','engine',43,false),
('exhaust-repair','Exhaust repair','repair_shop','exhaust',44,false),
('muffler','Muffler','repair_shop','exhaust',45,false),
('catalytic-converter','Catalytic converter','repair_shop','exhaust',46,false),
('pre-purchase-inspection','Pre-purchase inspection','repair_shop','inspection',47,false),
('lto-inspection','LTO inspection','repair_shop','inspection',48,false),
('emission-test','Emission test prep','repair_shop','inspection',49,false),
('roadside-assist','Roadside assist','repair_shop','mobile',50,false),
('mobile-mechanic','Mobile mechanic','repair_shop','mobile',51,false),
('scope-cars','Cars','repair_shop','vehicle_scope',60,false),
('scope-suvs','SUVs','repair_shop','vehicle_scope',61,false),
('scope-motorcycles','Motorcycles','repair_shop','vehicle_scope',62,false),
('scope-trucks','Trucks','repair_shop','vehicle_scope',63,false),
('scope-vans','Vans','repair_shop','vehicle_scope',64,false),
('scope-diesel','Diesel','repair_shop','vehicle_scope',65,false),
('scope-ev-hybrid','EV / Hybrid','repair_shop','vehicle_scope',66,false),
('scope-heavy-duty','Heavy duty','repair_shop','vehicle_scope',67,false),
-- BODY & PAINT
('collision-repair','Collision repair','body_paint','body',1,true),
('body-paint','Body & paint','body_paint','body',2,true),
('dent-removal-pdr','Dent removal (PDR)','body_paint','body',3,true),
('full-paint','Full paint','body_paint','paint',4,false),
('spot-paint','Spot paint','body_paint','paint',5,false),
('color-matching','Color matching','body_paint','paint',6,false),
('frame-straightening','Frame straightening','body_paint','body',7,false),
('bumper-repair','Bumper repair','body_paint','body',8,false),
('fender-repair','Fender repair','body_paint','body',9,false),
('plastic-welding','Plastic welding','body_paint','body',10,false),
('glass-replacement','Glass replacement','body_paint','glass',11,false),
('windshield-repair','Windshield repair','body_paint','glass',12,false),
('window-tinting','Window tinting','body_paint','glass',13,false),
('tint-removal','Tint removal','body_paint','glass',14,false),
('ceramic-coating','Ceramic coating','body_paint','protection',15,false),
('ppf','Paint protection film (PPF)','body_paint','protection',16,false),
('undercoating','Undercoating','body_paint','protection',17,false),
('rust-repair','Rust repair','body_paint','body',18,false),
('custom-paint','Custom paint','body_paint','paint',19,false),
('restoration','Restoration','body_paint','specialty',20,false),
('headlight-restoration','Headlight restoration','body_paint','specialty',21,false),
('motorcycle-paint','Motorcycle paint','body_paint','specialty',22,false),
('fleet-repair','Fleet repair','body_paint','specialty',23,false),
-- PARTS & ACCESSORIES
('oem-parts','OEM parts','parts_accessories','parts',1,true),
('aftermarket','Aftermarket','parts_accessories','parts',2,true),
('surplus-jdm','Surplus / JDM','parts_accessories','parts',3,false),
('performance-parts','Performance parts','parts_accessories','parts',4,false),
('body-kits','Body kits','parts_accessories','styling',5,false),
('led-hid','LED / HID lighting','parts_accessories','styling',6,false),
('audio-electronics','Audio & electronics','parts_accessories','electronics',7,false),
('dashcams','Dashcams','parts_accessories','electronics',8,false),
('alarms','Alarms','parts_accessories','electronics',9,false),
('gps-trackers','GPS trackers','parts_accessories','electronics',10,false),
('tires','Tires','parts_accessories','wheels',11,true),
('mags-wheels','Mags / wheels','parts_accessories','wheels',12,false),
('lift-kits','Lift kits','parts_accessories','suspension',13,false),
('lowering-kits','Lowering kits','parts_accessories','suspension',14,false),
('suspension-upgrades','Suspension upgrades','parts_accessories','suspension',15,false),
('brakes-upgrade','Brakes upgrade','parts_accessories','brakes',16,false),
('exhaust-systems','Exhaust systems','parts_accessories','performance',17,false),
('intake','Intake','parts_accessories','performance',18,false),
('ecu-tuning','ECU tuning','parts_accessories','performance',19,false),
('batteries','Batteries','parts_accessories','maintenance',20,false),
('lubricants','Lubricants','parts_accessories','maintenance',21,false),
('filters','Filters','parts_accessories','maintenance',22,false),
('belts-hoses','Belts & hoses','parts_accessories','maintenance',23,false),
('spark-plugs','Spark plugs','parts_accessories','maintenance',24,false),
('mirrors','Mirrors','parts_accessories','body',25,false),
('glass-parts','Glass','parts_accessories','body',26,false),
('interior-trim','Interior trim','parts_accessories','interior',27,false),
('seat-covers','Seat covers','parts_accessories','interior',28,false),
('floor-mats','Floor mats','parts_accessories','interior',29,false),
('roof-racks','Roof racks','parts_accessories','exterior',30,false),
('tow-hitches','Tow hitches','parts_accessories','exterior',31,false),
('motorcycle-parts','Motorcycle parts','parts_accessories','vehicle_scope',32,false),
('heavy-duty-parts','Heavy duty parts','parts_accessories','vehicle_scope',33,false),
('marine-parts','Marine parts','parts_accessories','vehicle_scope',34,false),
('accessories','General accessories','parts_accessories','styling',35,false),
-- DEALERSHIP
('brand-new','Brand new','dealership','condition',1,true),
('pre-owned','Pre-owned','dealership','condition',2,true),
('certified-pre-owned','Certified pre-owned','dealership','condition',3,false),
('repo-units','Repo units','dealership','condition',4,false),
('bank-financing','Bank financing','dealership','financing',5,true),
('inhouse-financing','In-house financing','dealership','financing',6,false),
('trade-in','Trade-in accepted','dealership','financing',7,false),
('low-downpayment','Low downpayment','dealership','financing',8,false),
('all-in-promo','All-in promo','dealership','financing',9,false),
('fleet-sales','Fleet sales','dealership','channel',10,false),
('government-bids','Government bids','dealership','channel',11,false),
('export-units','Export units','dealership','channel',12,false),
('brand-toyota','Toyota','dealership','brand',20,false),
('brand-honda','Honda','dealership','brand',21,false),
('brand-mitsubishi','Mitsubishi','dealership','brand',22,false),
('brand-nissan','Nissan','dealership','brand',23,false),
('brand-ford','Ford','dealership','brand',24,false),
('brand-hyundai','Hyundai','dealership','brand',25,false),
('brand-kia','Kia','dealership','brand',26,false),
('brand-suzuki','Suzuki','dealership','brand',27,false),
('brand-isuzu','Isuzu','dealership','brand',28,false),
('brand-mazda','Mazda','dealership','brand',29,false),
('brand-chevrolet','Chevrolet','dealership','brand',30,false),
('brand-byd','BYD','dealership','brand',31,false),
('brand-geely','Geely','dealership','brand',32,false),
('brand-mg','MG','dealership','brand',33,false),
('brand-foton','Foton','dealership','brand',34,false),
('brand-yamaha','Yamaha','dealership','brand',40,false),
('brand-kawasaki','Kawasaki','dealership','brand',41,false),
('brand-harley','Harley-Davidson','dealership','brand',42,false),
('brand-ducati','Ducati','dealership','brand',43,false),
('dealer-scope-cars','Cars','dealership','vehicle_scope',60,false),
('dealer-scope-suvs','SUVs','dealership','vehicle_scope',61,false),
('dealer-scope-motorcycles','Motorcycles','dealership','vehicle_scope',62,false),
('dealer-scope-trucks','Trucks','dealership','vehicle_scope',63,false),
('dealer-scope-vans','Vans','dealership','vehicle_scope',64,false),
-- CARWASH
('basic-wash','Basic wash','carwash','wash',1,true),
('full-detail','Full detail','carwash','detail',2,true),
('detailing','Detailing','carwash','detail',3,true),
('interior-cleaning','Interior cleaning','carwash','detail',4,false),
('leather-treatment','Leather treatment','carwash','detail',5,false),
('engine-wash','Engine wash','carwash','wash',6,false),
('underchassis-wash','Underchassis wash','carwash','wash',7,false),
('motorcycle-wash','Motorcycle wash','carwash','wash',8,false),
('hand-wax','Hand wax','carwash','protection',9,false),
('clay-bar','Clay bar','carwash','protection',10,false),
('headlight-polish','Headlight polish','carwash','detail',11,false),
('paint-correction','Paint correction','carwash','protection',12,false),
('cw-ceramic-coating','Ceramic coating','carwash','protection',13,false),
('ozone-treatment','Ozone treatment','carwash','detail',14,false),
('pet-hair-removal','Pet hair removal','carwash','detail',15,false),
-- TOWING
('flatbed','Flatbed','towing','equipment',1,true),
('wheel-lift','Wheel-lift','towing','equipment',2,false),
('heavy-duty','Heavy duty','towing','equipment',3,true),
('motorcycle-towing','Motorcycle towing','towing','equipment',4,true),
('long-distance','Long-distance','towing','service',5,false),
('accident-recovery','Accident recovery','towing','service',6,false),
('winch-out','Winch-out','towing','service',7,false),
('lockout','Lockout','towing','roadside',8,false),
('jumpstart','Jumpstart','towing','roadside',9,false),
('fuel-delivery','Fuel delivery','towing','roadside',10,false),
('tire-change-roadside','Roadside tire change','towing','roadside',11,false),
('dispatch-24-7','24/7 dispatch','towing','service',12,true),
('roadside','Roadside assistance','towing','roadside',13,true),
-- INSURANCE
('ctpl','CTPL','insurance','coverage',1,true),
('comprehensive','Comprehensive','insurance','coverage',2,true),
('motorcycle-insurance','Motorcycle insurance','insurance','coverage',3,true),
('fleet-insurance','Fleet insurance','insurance','coverage',4,false),
('tnvs-coverage','Ride-hail / TNVS coverage','insurance','coverage',5,false),
('gap-insurance','GAP insurance','insurance','coverage',6,false),
('acts-of-nature','Acts of nature','insurance','coverage',7,false),
('theft','Theft','insurance','coverage',8,false),
('third-party','Third-party','insurance','coverage',9,false),
('orcr-processing','OR/CR processing','insurance','service',10,false),
('claims-assist','Claims assist','insurance','service',11,false),
-- SALVAGE
('used-parts','Used parts','salvage','parts',1,true),
('oem-used','OEM used','salvage','parts',2,false),
('salvage-jdm','JDM surplus','salvage','parts',3,false),
('core-buyback','Core buyback','salvage','buyback',4,false),
('vehicle-buyback','Totaled vehicle buyback','salvage','buyback',5,false),
('parts-shipping','Parts shipping nationwide','salvage','logistics',6,false),
('pick-a-part','Pick-a-part yard','salvage','operations',7,false),
('motorcycle-salvage','Motorcycle salvage','salvage','vehicle_scope',8,false),
('truck-salvage','Truck salvage','salvage','vehicle_scope',9,false),
-- CROSS-CUTTING (NULL type_slug)
('pay-cash','Cash',NULL,'payment',1,true),
('pay-gcash','GCash',NULL,'payment',2,true),
('pay-maya','Maya',NULL,'payment',3,false),
('pay-credit-card','Credit card',NULL,'payment',4,false),
('pay-bank-transfer','Bank transfer',NULL,'payment',5,false),
('pay-installment','Installment',NULL,'payment',6,false),
('pay-cod','COD',NULL,'payment',7,false),
('cashless','Cashless transactions',NULL,'payment',8,true),
('24-7','Open 24/7',NULL,'hours',20,true),
('open-sundays','Open Sundays',NULL,'hours',21,false),
('by-appointment','By appointment',NULL,'hours',22,false),
('home-service','Home service',NULL,'service_mode',30,true),
('pickup-delivery','Pickup & delivery',NULL,'service_mode',31,false),
('mobile-service','Mobile service',NULL,'service_mode',32,false),
('walk-in','Walk-in welcome',NULL,'service_mode',33,false),
('warranty','Warranty offered',NULL,'trust',40,true),
('lto-accredited','LTO accredited',NULL,'trust',41,false),
('iso-certified','ISO certified',NULL,'trust',42,false),
('woman-owned','Woman-owned',NULL,'trust',43,false),
('family-owned','Family-owned',NULL,'trust',44,false),
('english-speaking','English-speaking staff',NULL,'trust',45,false),
('lang-filipino','Filipino spoken',NULL,'language',50,false),
('lang-english','English spoken',NULL,'language',51,false),
('lang-bisaya','Bisaya spoken',NULL,'language',52,false),
('lang-hokkien','Hokkien spoken',NULL,'language',53,false)
ON CONFLICT (slug) DO UPDATE SET
  label = EXCLUDED.label,
  type_slug = EXCLUDED.type_slug,
  category = EXCLUDED.category,
  sort_order = EXCLUDED.sort_order,
  is_popular = EXCLUDED.is_popular;
