INSERT INTO public.business_tags (slug, label, type_slug, category, sort_order, is_popular) VALUES
  ('fuel-gas-91', 'Gasoline 91', 'fuel_station', 'fuel_grade', 10, true),
  ('fuel-gas-95', 'Gasoline 95', 'fuel_station', 'fuel_grade', 20, true),
  ('fuel-gas-97', 'Gasoline 97', 'fuel_station', 'fuel_grade', 30, false),
  ('fuel-gas-100', 'Gasoline 100', 'fuel_station', 'fuel_grade', 40, false),
  ('fuel-diesel', 'Diesel', 'fuel_station', 'fuel_grade', 50, true),
  ('fuel-diesel-euro5', 'Premium Diesel (Euro 5)', 'fuel_station', 'fuel_grade', 60, false),
  ('fuel-biodiesel-b5', 'Bio-Diesel B5', 'fuel_station', 'fuel_grade', 70, false),
  ('fuel-e10', 'E10 / Ethanol blend', 'fuel_station', 'fuel_grade', 80, false),
  ('fuel-kerosene', 'Kerosene', 'fuel_station', 'fuel_grade', 90, false),
  ('fuel-avgas', 'AvGas', 'fuel_station', 'fuel_grade', 100, false),
  ('fuel-autogas-lpg', 'Autogas (LPG)', 'fuel_station', 'fuel_grade', 110, false),
  ('fuel-cng', 'CNG', 'fuel_station', 'fuel_grade', 120, false),

  ('ev-type2-ac', 'Type 2 AC', 'fuel_station', 'ev_charging', 200, true),
  ('ev-ccs2-dc', 'CCS2 DC', 'fuel_station', 'ev_charging', 210, true),
  ('ev-chademo', 'CHAdeMO', 'fuel_station', 'ev_charging', 220, false),
  ('ev-tesla-nacs', 'Tesla / NACS', 'fuel_station', 'ev_charging', 230, false),
  ('ev-7kw', '7 kW', 'fuel_station', 'ev_charging', 240, false),
  ('ev-22kw', '22 kW', 'fuel_station', 'ev_charging', 250, false),
  ('ev-50kw', '50 kW', 'fuel_station', 'ev_charging', 260, false),
  ('ev-150kw-plus', '150 kW+', 'fuel_station', 'ev_charging', 270, false),
  ('ev-24-7-charging', '24/7 charging', 'fuel_station', 'ev_charging', 280, false),

  ('station-convenience-store', 'Convenience store', 'fuel_station', 'station_services', 300, true),
  ('station-restrooms', 'Restrooms', 'fuel_station', 'station_services', 310, false),
  ('station-atm', 'ATM', 'fuel_station', 'station_services', 320, false),
  ('station-air-water', 'Air & water', 'fuel_station', 'station_services', 330, false),
  ('station-car-wash', 'Car wash', 'fuel_station', 'station_services', 340, false),
  ('station-lube-bay', 'Lube bay', 'fuel_station', 'station_services', 350, false),
  ('station-tire-service', 'Tire service', 'fuel_station', 'station_services', 360, false),
  ('station-lpg-refill', 'LPG refill', 'fuel_station', 'station_services', 370, false),
  ('station-24-7', '24/7 open', 'fuel_station', 'station_services', 380, true),
  ('station-loyalty-card', 'Loyalty card accepted', 'fuel_station', 'station_services', 390, false),
  ('station-fleet-card', 'Fleet card accepted', 'fuel_station', 'station_services', 400, false)
ON CONFLICT (slug) DO NOTHING;