
ALTER TABLE public.business_inventory_items
  ADD COLUMN IF NOT EXISTS barcode text,
  ADD COLUMN IF NOT EXISTS manufacturer_part_number text,
  ADD COLUMN IF NOT EXISTS main_category text,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS manufacturer text,
  ADD COLUMN IF NOT EXISTS supplier text,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS markup_percentage numeric,
  ADD COLUMN IF NOT EXISTS date_purchased date,
  ADD COLUMN IF NOT EXISTS last_price_update date,
  ADD COLUMN IF NOT EXISTS qty_on_hold numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qty_on_order numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_stock_level numeric,
  ADD COLUMN IF NOT EXISTS max_stock_level numeric,
  ADD COLUMN IF NOT EXISTS weight_lbs numeric,
  ADD COLUMN IF NOT EXISTS dimensions text,
  ADD COLUMN IF NOT EXISTS color text,
  ADD COLUMN IF NOT EXISTS material text,
  ADD COLUMN IF NOT EXISTS model_year integer,
  ADD COLUMN IF NOT EXISTS oem_part_number text,
  ADD COLUMN IF NOT EXISTS warranty_period text,
  ADD COLUMN IF NOT EXISTS universal_part boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tax_rate numeric,
  ADD COLUMN IF NOT EXISTS environmental_fee numeric,
  ADD COLUMN IF NOT EXISTS core_charge numeric,
  ADD COLUMN IF NOT EXISTS hazmat_fee numeric,
  ADD COLUMN IF NOT EXISTS tax_exempt boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS date_last_ordered date,
  ADD COLUMN IF NOT EXISTS date_last_used date,
  ADD COLUMN IF NOT EXISTS web_links jsonb NOT NULL DEFAULT '[]'::jsonb;
