ALTER TABLE public.business_tags ADD COLUMN IF NOT EXISTS description text;

UPDATE public.business_tags SET description = 'Patching a punctured tire by heat-bonding a rubber patch from the inside.' WHERE slug = 'tire-vulcanizing';
UPDATE public.business_tags SET description = 'Patching a punctured tire by heat-bonding a rubber patch from the inside.' WHERE slug = 'rs-tire-vulcanizing';
UPDATE public.business_tags SET description = 'Sealing punctures and minor tire damage with patches or plugs.' WHERE slug = 'tire-repair-patch';
UPDATE public.business_tags SET description = 'Sealing punctures and minor tire damage with patches or plugs.' WHERE slug = 'rs-tire-repair-patch';
UPDATE public.business_tags SET description = 'Installing tires on rims and balancing them for a smooth, vibration-free ride.' WHERE slug = 'tire-mount-balance-ts';
UPDATE public.business_tags SET description = 'Adjusting wheel angles so tires wear evenly and the vehicle tracks straight.' WHERE slug = 'ts-alignment';
UPDATE public.business_tags SET description = 'Balancing wheel-tire assemblies to eliminate vibrations at speed.' WHERE slug = 'ts-wheel-balancing';
UPDATE public.business_tags SET description = 'Tire Pressure Monitoring System — servicing sensors that warn of low tire pressure.' WHERE slug = 'ts-tpms';
UPDATE public.business_tags SET description = 'Repairing bent, cracked, or scraped alloy / mag wheels.' WHERE slug = 'mag-wheel-repair';
UPDATE public.business_tags SET description = 'Periodic swapping of tire positions to promote even tread wear.' WHERE slug = 'tire-rotation';
UPDATE public.business_tags SET description = 'Inflating tires with nitrogen for more stable pressure and slower leakage.' WHERE slug = 'tire-nitrogen';
UPDATE public.business_tags SET description = 'Converting spoked or tubed wheels to tubeless for easier maintenance.' WHERE slug = 'tire-tubeless-conversion';
UPDATE public.business_tags SET description = 'On-site tire assistance when you get a flat away from the shop.' WHERE slug = 'tire-flat-roadside';
UPDATE public.business_tags SET description = 'Applying new tread to a worn tire casing to extend service life.' WHERE slug = 'tire-recap-retread';
UPDATE public.business_tags SET description = 'New passenger, SUV, truck, and motorcycle tires in stock.' WHERE slug = 'inv-tire-new';
UPDATE public.business_tags SET description = 'Pre-owned tires inspected for safety and remaining tread depth.' WHERE slug = 'inv-tire-used';
UPDATE public.business_tags SET description = 'Alloy and steel rims, including custom-fit options for various vehicles.' WHERE slug = 'inv-tire-mags';
UPDATE public.business_tags SET description = 'Available around the clock for emergency tire repairs and blowouts.' WHERE slug = 'tire-24-7';
UPDATE public.business_tags SET description = 'Tire technician comes to your home, office, or roadside location.' WHERE slug = 'tire-mobile-service';
UPDATE public.business_tags SET description = 'Air-conditioning repair, recharge, and leak detection for vehicles.' WHERE slug = 'aircon';
UPDATE public.business_tags SET description = 'Scheduled engine oil and filter change to keep the motor running clean.' WHERE slug = 'oil-change';
UPDATE public.business_tags SET description = 'Collision repair, dent removal, and respray to restore vehicle appearance.' WHERE slug = 'body-paint';
UPDATE public.business_tags SET description = 'Deep interior and exterior cleaning, polishing, and paint protection.' WHERE slug = 'detailing';
UPDATE public.business_tags SET description = 'Battery, alternator, wiring, and electronic diagnostics and repair.' WHERE slug = 'electrical';
UPDATE public.business_tags SET description = 'Restoring worn brake pads, discs, and hydraulic components for safe stopping.' WHERE slug = 'brakes';
UPDATE public.business_tags SET description = 'Computerized scanning to identify engine, transmission, and system faults.' WHERE slug = 'diagnostics';
UPDATE public.business_tags SET description = 'Transmission, differential, and drive axle service and repair.' WHERE slug = 'drivetrain';
UPDATE public.business_tags SET description = 'Engine overhaul, timing, and cooling system maintenance.' WHERE slug = 'engine';
UPDATE public.business_tags SET description = 'Radiator, coolant, and thermostat repairs to prevent overheating.' WHERE slug = 'cooling';
UPDATE public.business_tags SET description = 'Shocks, struts, and steering linkage inspection and replacement.' WHERE slug = 'suspension';
UPDATE public.business_tags SET description = 'Heater, A/C compressor, and climate control repairs.' WHERE slug = 'climate';
UPDATE public.business_tags SET description = 'Muffler, catalytic converter, and exhaust pipe repair or replacement.' WHERE slug = 'exhaust';
UPDATE public.business_tags SET description = 'Automated or hand car wash services.' WHERE slug = 'wash';
UPDATE public.business_tags SET description = 'Paint correction, ceramic coating, and protective film application.' WHERE slug = 'paint';
UPDATE public.business_tags SET description = 'Dent removal, panel beating, and structural body repair.' WHERE slug = 'body';
UPDATE public.business_tags SET description = 'Windshield and window repair or replacement.' WHERE slug = 'glass';
UPDATE public.business_tags SET description = 'Services delivered at your location rather than at the shop.' WHERE slug = 'mobile';
UPDATE public.business_tags SET description = 'Towing, jump-starts, and emergency assistance when stranded.' WHERE slug = 'roadside';
UPDATE public.business_tags SET description = 'Pre-purchase or annual roadworthiness and safety inspection.' WHERE slug = 'inspection';
UPDATE public.business_tags SET description = 'ECU tuning, turbo, intake, and performance upgrades.' WHERE slug = 'performance';
UPDATE public.business_tags SET description = 'Niche or specialized repairs for classic, luxury, or modified vehicles.' WHERE slug = 'specialty';
UPDATE public.business_tags SET description = 'Original Equipment Manufacturer parts — genuine factory components.' WHERE slug = 'oem-parts';
UPDATE public.business_tags SET description = 'Third-party replacement and upgrade parts at various price points.' WHERE slug = 'aftermarket';
UPDATE public.business_tags SET description = 'Vehicle batteries for cars, SUVs, trucks, and motorcycles.' WHERE slug = 'batteries';
UPDATE public.business_tags SET description = 'Interior and exterior accessories, add-ons, and styling parts.' WHERE slug = 'accessories';
UPDATE public.business_tags SET description = 'Flatbed truck transport for damaged or non-running vehicles.' WHERE slug = 'flatbed';
UPDATE public.business_tags SET description = 'Towing for buses, trucks, and heavy commercial equipment.' WHERE slug = 'heavy-duty';
UPDATE public.business_tags SET description = 'Towing and roadside assistance specifically for motorcycles.' WHERE slug = 'motorcycle-towing';
UPDATE public.business_tags SET description = 'Compulsory Third Party Liability insurance — legally required coverage.' WHERE slug = 'ctpl';
UPDATE public.business_tags SET description = 'Full vehicle insurance covering theft, collision, and Acts of God.' WHERE slug = 'comprehensive';
UPDATE public.business_tags SET description = 'Insurance packages tailored for motorcycles and scooters.' WHERE slug = 'motorcycle-insurance';
UPDATE public.business_tags SET description = 'Open 24 hours a day, 7 days a week.' WHERE slug = '24-7';
UPDATE public.business_tags SET description = 'Technician or service team comes to your location.' WHERE slug = 'home-service';
UPDATE public.business_tags SET description = 'Service or parts backed by a manufacturer or shop warranty.' WHERE slug = 'warranty';
UPDATE public.business_tags SET description = 'Accepts credit cards, debit cards, or digital wallets.' WHERE slug = 'cashless';
UPDATE public.business_tags SET description = 'Pre-owned cars, trucks, SUVs, and vans inspected for resale.' WHERE slug = 'used';
UPDATE public.business_tags SET description = 'Brand-new vehicles straight from the manufacturer or distributor.' WHERE slug = 'new';
UPDATE public.business_tags SET description = 'Standard unleaded gasoline with 91 octane rating.' WHERE slug = 'fuel-gas-91';
UPDATE public.business_tags SET description = 'Premium unleaded gasoline with 95 octane rating.' WHERE slug = 'fuel-gas-95';
UPDATE public.business_tags SET description = 'High-octane unleaded gasoline with 97 rating for performance engines.' WHERE slug = 'fuel-gas-97';
UPDATE public.business_tags SET description = 'Top-tier unleaded gasoline with 100 octane for high-compression engines.' WHERE slug = 'fuel-gas-100';
UPDATE public.business_tags SET description = 'Standard diesel fuel for cars, SUVs, and commercial vehicles.' WHERE slug = 'fuel-diesel';
UPDATE public.business_tags SET description = 'Cleaner-burning premium diesel meeting Euro 5 emission standards.' WHERE slug = 'fuel-diesel-euro5';
UPDATE public.business_tags SET description = 'Diesel blended with 5% biodiesel for reduced emissions.' WHERE slug = 'fuel-biodiesel-b5';
UPDATE public.business_tags SET description = 'Gasoline blended with 10% ethanol — common eco-fuel option.' WHERE slug = 'fuel-e10';
UPDATE public.business_tags SET description = 'Kerosene for heaters, lamps, and certain commercial engines.' WHERE slug = 'fuel-kerosene';
UPDATE public.business_tags SET description = 'Aviation gasoline for light aircraft and aeroclub use.' WHERE slug = 'fuel-avgas';
UPDATE public.business_tags SET description = 'Liquefied Petroleum Gas — alternative fuel for LPG-converted vehicles.' WHERE slug = 'fuel-autogas-lpg';
UPDATE public.business_tags SET description = 'Compressed Natural Gas — cleaner-burning alternative fuel.' WHERE slug = 'fuel-cng';
UPDATE public.business_tags SET description = 'Standard AC charging socket for electric vehicles.' WHERE slug = 'ev-type2-ac';
UPDATE public.business_tags SET description = 'Combined Charging System 2 — fast DC charging for EVs.' WHERE slug = 'ev-ccs2-dc';
UPDATE public.business_tags SET description = 'Japanese-standard fast DC charging socket for EVs.' WHERE slug = 'ev-chademo';
UPDATE public.business_tags SET description = 'Tesla / North American Charging Standard fast DC connector.' WHERE slug = 'ev-tesla-nacs';
UPDATE public.business_tags SET description = '7 kilowatt AC charger — typical home or office wallbox speed.' WHERE slug = 'ev-7kw';
UPDATE public.business_tags SET description = '22 kilowatt AC charger — fast three-phase workplace charging.' WHERE slug = 'ev-22kw';
UPDATE public.business_tags SET description = '50 kilowatt DC fast charger — highway and commercial stop speeds.' WHERE slug = 'ev-50kw';
UPDATE public.business_tags SET description = '150+ kilowatt ultra-fast DC charger — quickest public EV charging.' WHERE slug = 'ev-150kw-plus';
UPDATE public.business_tags SET description = 'EV chargers accessible any time of day or night.' WHERE slug = 'ev-24-7-charging';