// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

// Production authentication must never fall back to the retired Lovable project.
// These are public browser credentials (not the service-role secret). Keeping the
// canonical standalone values here also protects production from stale Vite build
// variables cached by a hosting provider.
const STANDALONE_SUPABASE_URL = "https://wjxaajgvddtrxxtocxen.supabase.co";
const STANDALONE_SUPABASE_PUBLISHABLE_KEY =
  "sb_publishable_RTI8m0ZvjoZFH7_q-wnIQQ_SxrL0s-d";

function createSupabaseClient() {
  return createClient<Database>(
    STANDALONE_SUPABASE_URL,
    STANDALONE_SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    },
  );
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
